### ISSUE TITLE
Uranium spawning in the world?

### ISSUE THREAD

**Issue by Dominance** [AdlyTempleton/MineChem#101]
Well this is very strange as to my understanding you do not have world gen inside Mine Chem. Right now only in a vanilla biome so far that I have found. I am seeing a massive amount of uranium ore from Minechem

Here is a quick screen shot of the ore spawn
http://www.mcbeyondreality.com/downloads/2013-12-05_00.45.50.png

This is a link to all the mods currently installed
http://www.atlauncher.com/packs/BeyondReality/ running version 4-10 of minechem with forge 953. IC2 and gregtech are installed. Tried the ol 0 trick but yeah no go :(

Edit: This is was found on our server running MCPC+

**Comment by AdlyTempleton** [comment]
Fixed a while ago.
