### ISSUE TITLE
Proposal: Allow decomposition of items based on their recipe

### ISSUE THREAD

**Issue by mctynp** [AdlyTempleton/MineChem#102]
Motivation:
(1) Provide a use for all those badly-damaged items dropped by mobs
(2) Make Minechem more useful in general

I suggest adding a way to decompose most items based on their recipe. For example, decomposing a stone pickaxe would be equivalent to decomposing two sticks and three cobblestone blocks. Damaged items could return results proportional to the damage level (e.g., a stone pickaxe at 10% would return 10% as much as one at 100%).

I am not suggesting synthesis recipes be added for these items; breaking items down into their components seems to be in the spirit of Minechem, but assembling complex items from random parts isn't.

**Comment by AdlyTempleton** [comment]
Problem is, this creates large amounts of dupe bugs. Look at all the bugs with twilight forest's uncrafting table.

**Comment by mctynp** [comment]
This could be restricted to items with only a single recipe. Or, items with multiple recipes could have the "cheapest" recipe picked (e.g., based on carbon output, if diamond generation is a concern). Blacklisting or whitelisting could be used as well. All ad hoc recipes could be scaled to return less than the sum of their inputs, as well (e.g., 50% always lost).

I've been playing with a limited version of this (only vanilla recipes plus ones from a mod for which I wrote a recipe adapter) prior to suggesting it, and it's really nice to get an Fe or Au or two from that battered helm from the zombies that mobbed my front door. :)

**Comment by jakimfett** [comment]
This is already implemented to a certain extent. Because of duplication possibilities, it's somewhat restricted.

I'll keep this in mind for the 5.1.x enhancements, but for now, I'm closing it to clean up the issues list.
