### ISSUE TITLE
Proposal: Add easy way for custom recipes involving any items

### ISSUE THREAD

**Issue by mctynp** [AdlyTempleton/MineChem#103]
Motivation:
(1) Make it easy for other mods to integrate with Minechem
(2) Make it easy to create new decomposition or synthesis recipes.

I propose adding an easy way to add new Minechem decomposer or synthesis recipes. I suggest a method based on config files, where any mod can define a set of recipes in a stanza whose contents are handled by Minechem. For example, Forestry might add a separate config file (or stanza in its own configs) like:

customMinechemRecipes {
  apatiteDecompose {
    S:RecipeType=Decomposer
    # Ca10(PO4)6(OH)2
    S:Input=item.apatite
    S:Output <
        minechem.element.Ca:10
        minechem.molecule.phosphate:6
        minechem.molecule.hydroxide:2
    >
  }

  apatiteSynthesis {
    S:RecipeType=ShapedSynthesis
    S:Input <
        none:0
        minechem.element.Ca:6
        none:0
        minechem.element.Ca:2
        minechem.molecule.phosphate:6
        minechem.element.Ca:2
        none:0
        minechem.molecule.hydroxide:2
        none:0
    >
    S:Output=item.apatite
    I:Cost=1000
  }
}

which would define a new decomposition recipe for Forestry's apatite, and a new shaped synthesis recipe to synthesize it.

For convenience, decomposer recipes could also list any item in its output (not just Minechem chemicals) as long as there's a decomposition recipe for that item. The decomposer recipe would be treated as the sum of all sub-recipes. For example, a Buildcraft stone gear might list its output as:
  S:Output <
      tile.stonebrick:4
      item.stick:4

and a Forestry bronze gear might list its output as:
  S:Output <
    item.ingotBronze:4
    item.stoneGearItem

to show its output is the sum of what's yielded from decomposing 4 bronze ingots plus one stone gear.

Minechem currently has some support for custom decomposition recipes, but it requires hardcoded numeric IDs and a rigid format added directly to the Minechem config.

**Comment by AdlyTempleton** [comment]
Honestly, this is planned for after 1.7. Any config system will have to be rewritten for 1.7 anyway.

**Comment by mctynp** [comment]
It only took a few days to implement most of this (I've been playing with a prototype version for a while now) so I don't think rewriting it for 1.7.x would be a huge deal. Is Forge for 1.7.x+ going to completely redo their configuration handler and/or config file format?

The most complex part is finding subtyped items by name, but even that isn't too crazy (there's a hacky way involving creative tab enumeration). I'd hope 1.7.x would make it easier.

**Comment by AdlyTempleton** [comment]
Forge 1.7 is going to remove item ids, which would change any config file format. Also, if I'm going to do this right, I won't be using forge config system, I'll be using a .json or somesuch.
