### ISSUE TITLE
[Suggestion] Make Mycotoxin also grow mushrooms on the player

### ISSUE THREAD

**Issue by Vexatos** [AdlyTempleton/MineChem#112]
Just for fun, I know that the toxin itself does not do this. But hey, it's Minecraft, why not having chemicals behave a little different than IRL? :D

**Comment by MFernflower** [comment]
That would require some insane rendering code. And while a lot of things are somewhat sticking to reality. There will be some nonsensical macrocyclic compounds added. I promise!

**Comment by jakimfett** [comment]
Yeah, the insane rendering for this makes it a bit too complex to add right now. But I'll keep it in mind...maybe pouring mycotoxin on soil will make it into mycelium.
