### ISSUE TITLE
Polytool, new stuff, no read me, no explanations...

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [AdlyTempleton/MineChem#119]
Y'all are adding so much new stuff, so many changes. I get that a read me sort of becomes pointless after a few commits, however, with the recent polytool thingamajing it'd be nice if there were some sort of explanation about all the new stuff y'all are adding and how it works.

Just the basics, so folks can expirement and find it out by themselves.

**Comment by MFernflower** [comment]
I agree

**Comment by AdlyTempleton** [comment]
http://pixlepixmods.wordpress.com/2013/12/31/polytools-are-released/

Polytool uses for any individual element can be found by shifting over the item description.

New website coming soon, within the week if all goes well.
