### ISSUE TITLE
[3.x.73] Cannot interact with player inventory while Chemical Fusion Chamber is open.

### ISSUE THREAD

**Issue by Timeslice42** [AdlyTempleton/MineChem#12]
While the GUI for the Chemical Fusion Chamber is open it is impossible to interact with anything in the player's inventory, which also makes it impossible to put anything in the chamber.

This issue was fixed half of the time in build 63, but seems to have gotten much worse in the most recent build.

**Comment by Timeslice42** [comment]
_Update_ Every block seems to be broken except for the last one that you placed, which seems to work just fine.

**Comment by Timeslice42** [comment]
Confirmed still broken in 115.

**Comment by jfreuden** [comment]
Why was this issue closed? This is still a problem.

**Comment by Timeslice42** [comment]
He decided that having the interface work on only one block and bug out on the rest was "good enough". 

----- Original Message -----

**Comment by Rushmead** [comment]
We Are ReWriting The Multiblock COde Over The 1.6.2 Update

**Comment by jfreuden** [comment]
This is good to hear. Timeslice, would you mind telling me which block works? Is it random?
