### ISSUE TITLE
[Crash] Rightclicking a ghostblock

### ISSUE THREAD

**Issue by thatsIch** [AdlyTempleton/MineChem#121]
http://paste.ee/r/Njnih

**Comment by AdlyTempleton** [comment]
Added in a quick fix. Leaving it open as it seems to be a symptom of a larger problem

**Comment by jakimfett** [comment]
I'm going ahead and closing this. I've seen similar crashes in other sections of the code, and in most places, they can be avoided by checking to make sure an object isn't null before calling its functions.
