### ISSUE TITLE
IndexOutOfBoundsException: Some or other NEI Decomposer crash

### ISSUE THREAD

**Issue by taljaards** [AdlyTempleton/MineChem#122]
Using 5.0.0p3:
http://paste.ee/p/UUhmx

**Comment by taljaards** [comment]
I tested, it's caused by pressing U (to see what recipes it is used in [NEI]) on IronChests mod's Iron Chest.
I haven't tested the other chests from that mod.

**Comment by AdlyTempleton** [comment]
Fixed, thanks for the report.
