### ISSUE TITLE
Duplication with Recipes Involving More Than One Output Item

### ISSUE THREAD

**Issue by MrBrix123** [AdlyTempleton/MineChem#124]
This duplication requires an example:
A torch will decompose into 30 carbon and one cellulose.
The cellulose can be synthesized into a stick, and the carbon can be synthesized into 1 coal (with 14 carbon extra) or one charcoal (no extra carbon).
Now this happens to let us make four torches and repeat.

This works with any recipe that outputs more than one item except the ones that you did yourself (ex: diamond block-->diamonds).

BTW: Good work with this mod, and hello (it was unfortunate to see you leave OTE)

**Comment by AdlyTempleton** [comment]
Fixed in 5.0.1p2
