### ISSUE TITLE
(Minechem 5.02 - Server Crash) Ticking Memory Connection

### ISSUE THREAD

**Issue by Vaygrim** [AdlyTempleton/MineChem#126]
MultiMC crash log - http://paste.ee/p/SwDDP
Console log - http://paste.ee/p/AcSIb

Minecraft 1.6.4 / Forge 965
Minechem 5.02 (downloaded 2 days ago)

I had just used a Fission Chamber to split some Tungsten, and saw a "Server crash" error code in the console log. The client had NOT halted yet however. It took the client about a minute to actually finally catch up and crash, and in the mean time I cannot interact with anything.

World save reloads fine, but I am getting this crash pretty routinely when interacting at all with the Fission Chamber (have not used the Fusion Chamber yet).

**Comment by Rushmead** [comment]
Fix For @pixlepix : null check on line 110!
