### ISSUE TITLE
Projector Blueprint Dup bug.

### ISSUE THREAD

**Issue by Arctic-Wolfy** [AdlyTempleton/MineChem#131]
I took the blue print out then exited out of the GUI and broke the projector and it dropped itself and another blueprint.

**Comment by AdlyTempleton** [comment]
Can't reproduce this.

**Comment by cardenaso11** [comment]
I am familiar with this bug, and it only happens when the blueprint is removed via a shift-left click. :D

**Comment by jakimfett** [comment]
Closing for now. Need to rework some of the GUI code.
