### ISSUE TITLE
Generating Buckets - Pam's HarvestCraft

### ISSUE THREAD

**Issue by Sohala123** [AdlyTempleton/MineChem#142]
Fresh Water from Pam's HarvestCraft is being read as having iron in it. This is presently resulting in iron being generated from it.

Any method of changing the output of items?

**Comment by jakimfett** [comment]
This actually isn't a bug. To make Fresh Water, you use a bucket full of water...which requires 3 iron to make. Here's the comparison:
![](http://pics.jakimfett.com/14-5-10_10:07:22.png)
And the crafting recipe:
![](http://pics.jakimfett.com/14-5-10_10:09:15.png)

**Comment by Sohala123** [comment]
An empty bucket remains after making the Fresh Water, which results in the iron from the Fresh Water being generated. Seemingly, the bucket is merely a container and the water is the only thing being used.

**Comment by jakimfett** [comment]
Oh, I somehow completely missed that. I'll see if I can put together a fix for this.

**Comment by jakimfett** [comment]
I've fixed this in code, it'll be in the next release.
