### ISSUE TITLE
Crash with Chemical Decomposer

### ISSUE THREAD

**Issue by laguy442** [AdlyTempleton/MineChem#144]
Placing an empty test tube into the input slot on a Chemical Decomposer causes it to crash Minecraft.  Playing on version 5.0.4 from Resonant Rise Pack.  Was able to reproduce issue on both server and SSP.

http://pastebin.com/z5DMP1Um

**Comment by jakimfett** [comment]
This will be fixed in the next dev build, thanks for reporting it.
