### ISSUE TITLE
Particle accelerator part not working

### ISSUE THREAD

**Issue by ghost** [AdlyTempleton/MineChem#145]
The whole particle accelerator part of the mod doesn't work for me. I also used NEI, CodeChickenCore, CoFH core and Thermal expansion 3

**Comment by cardenaso11** [comment]
Make sure you've it downloaded it, if I recall correctly it is a sub-mod
(module).

**Comment by jakimfett** [comment]
@noshiz1995 - What version of Minechem are you running? Particle physics can be a bit confusing to set up, I highly recommend [watching Bevo's video on Minechem](https://www.youtube.com/watch?feature=player_detailpage&v=V_J7eruam9A#t=1058), which explains how to set up an accelerator, and how to generate power with it.

I was able to set up a particle accelerator using Minechem 5.0.5-Dev3, so I'm going to go ahead and close this ticket. If you have more info, or can provide steps to reproduce the bug, I'll re-open it.
![](http://pics.jakimfett.com/14-5-10_10:30:46.png)
![](http://pics.jakimfett.com/14-5-10_10:31:24.png)
