### ISSUE TITLE
Chemicals not stacking

### ISSUE THREAD

**Issue by CocoaMix86** [AdlyTempleton/MineChem#147]
Why do chemicals of the same kind not stack? This is bugging me and it breaks my sorting system.
![2014-03-20_19 24 35](https://f.cloud.github.com/assets/5726733/2479643/5fbfa458-b09e-11e3-9874-1ea552696554.png)

**Comment by MFernflower** [comment]
Will be fixed in PR #150

**Comment by jakimfett** [comment]
@CocoaMix86 - I'm going to be releasing a dev build in a couple of hours, you up for testing it?

**Comment by CocoaMix86** [comment]
if it's for mc1.6.4, then yes

**Comment by jakimfett** [comment]
Yup. You can get it from the [releases page](https://github.com/jakimfett/MineChem/releases/tag/1.6.4-5.0.5-Dev) on my Github fork, or via curseforge.

**Comment by CocoaMix86** [comment]
Thanks for the dev build! Now all my chemicals so far stack properly! :D
![2014-04-22_17 03 24](https://cloud.githubusercontent.com/assets/5726733/2771379/0d636d80-ca6a-11e3-9fb8-440f2c2d880a.png)

**Comment by jakimfett** [comment]
No problem, glad it worked for ya!
