### ISSUE TITLE
Dupe bug 

### ISSUE THREAD

**Issue by Perryman** [AdlyTempleton/MineChem#149]
Using a router from the factorization mod and extracting from slot 0 produces unlimited copies of the output and does not consume the ingredients in the bottom area. Tested only with nether star recipe so far. I'm not sure if this is a problem with factorization or minechem, but due to the severity if verified, I figured it was worth posting here. Running on resonant rise 2.7.2.2-RR, factorization 0.8.34, minechem 5.0.4, forge #965.

**Comment by Belgabor** [comment]
Same issue with SFM.

**Comment by jakimfett** [comment]
@Belgabor - SFM? Single Frozen Malt? Little bit more explanation would be awesome...

**Comment by Belgabor** [comment]
Steve's Factory Manager. Sorry, the abbreviation became so common whenever I read about it and  assumed, given it's epicness, everybody would be aware of it =)

**Comment by jakimfett** [comment]
@Perryman - I can't seem to reproduce this. Using a factorization router, it does pull from the decomposer, but it removes the items, it doesn't copy or dupe them.

I'd also be interested in getting input from @Belgabor, given that I'm not sure if this was originally a Minechem problem or something with the other mods.

I'm running Minechem 5.0.5-Dev3 with Factorization 0.8.34. If you're able to reproduce this with the latest version of the mods, I'll go ahead and re-open it.
