### ISSUE TITLE
Shift-clicking crash

### ISSUE THREAD

**Issue by drakray** [AdlyTempleton/MineChem#151]
With the decomposer, shift-clicking certain item crash and corrupt world
Must remove decomposer with MCE
Minechem 5.0.4

Crash with Pam's HarvestCraft Candle
Candle show molecule with NEI

http://pastebin.com/hY9F5syj

**Comment by jakimfett** [comment]
Is the candle the only item that has this problem?

**Comment by drakray** [comment]
there was other, but it's the only one I remember right now
some of the other had different crash log, array out of bound and the such
I'll try to get more crash with the decomposer the next time I test MC

**Comment by jakimfett** [comment]
If you can put together a list of these, it'd make fixing it a whole bunch easier. There are two other bugs reported for the decomposer and specific items, but I haven't been able to reproduce either of them (crash with leather helmet and stone sword).

Most important part is reproducibility. If I can't make the crash happen, I can't debug it, or code a fix. When the crash happens, make sure you can make it happen again.

Oh, and if you're not already running the latest version from CurseForge, now would be a good time to update.

**Comment by drakray** [comment]
i'll put a list as soon as I can, I can also give you my mod list and config
I already use the latest version, 5.0.4 of minechem
I tend to always keep my mod up to date, in the Mc I use (1.6.4 in this instance)

**Comment by jakimfett** [comment]
Sweet, thanks! If you've got any questions, feel free to ping me in #jakimfett on the Esper.net IRC.

**Comment by jakimfett** [comment]
This should be fixed in dev3

**Comment by drakray** [comment]
When will it be available on Curse? :)

**Comment by jakimfett** [comment]
Not sure, @Drakray. Curse is being dumb about file uploads right now...claims I already uploaded it.

**Comment by drakray** [comment]
ok, there is only DEV2 on Curse, is there another place I can get it?

**Comment by MFernflower** [comment]
When I get home. I can build the latest src and dropbox it

**Comment by jakimfett** [comment]
Curse is being problematic at the moment, I added a link to the readme for downloading [directly from Github](https://github.com/jakimfett/MineChemDev/releases). @Drakray
