### ISSUE TITLE
No information about what the different molecules for weapon coating do

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [AdlyTempleton/MineChem#153]
Title says it all. There's no information anywhere to be read up as to what the different molecules do that can be coated on weapons like testosterone, psycobilin, penicillin, etc.

**Comment by jakimfett** [comment]
Coating a weapon applies the effect from the chemical to whatever entity you hit. The effects are the same as if you'd eaten some food laced with the chemical, or if you simply drank the chemical.

As a side note, hitting a creeper with a cocaine coated sword is funny...but only until you realize that you can't outrun the creeper.

**Comment by Webmetz** [comment]
Here is a list that does not list fire/damage effects, just the status effects.

Mescaline (Blindness and Nausea),
Psilocybin (night vision and nausea)
Methamphetamine/amphetamine (1 minute speed, 30 sec nausea)
Asparatic Acid/Alanine/Valine/Arganine/Asparagine/Cysteine/Threonine/Methonine/Tyrosine/Proline/Lieucine/Phenylalanine/Histidine/Isoeucine (Haste+Jump Boost 4 for 2 minutes).
Potassium Cyanide (Wither 2 minutes)
Ethyl Alchol (Nausea 30 seconds)
Penicillin/Asprin (Regeneration 5/3 minutes)
Theobromine (Speed/Haste 5 minutes)
Pantherine (3 minute Slowness 3 and Nausea)
Testosterone (Speed 2 and Strength 2 for 3 minutes)
Fingolimod (Hunger 2 5 minutes, Speed/Strength/Regeneration 2 1 minute)
Alprazolam   Slowness IV     3:30    Nausea IV   3:30
Batrachotoxin    Slowness    1:00    Wither III  1:00    Nausea III  1:00
Caulerpenyne     Weakness    2:00    Nausea  2:00
Cocaine Hydrochloride    Speed   _:_\*    Night Vision    _:_\*    Nausea  _:_*
Cocaine  Speed   2:00    Night Vision    2:00    Nausea  2:00
Diphenydramine   Nausea  0:40
Hyoscyamine  Slowness III    2:00    Water Breathing II  2:00    Nausea III  2:00
Methylene Alchohol   Wither III  2:00    Blindness   2:00
Methylene Blue   Weakness    0:30    Regeneration    0:30
Radium Chloride  Poison  1:00    Weakness    1:00    Wither II   0:30
Retinol  Night Vision    5:00
Sucrose  Speed II    0:40
T-2 Mycotoxin    Wither  4:00    Weakness    4:00
Tetrodotoxin     Wither II   0:30    Slowness    0:30
THC  Hunger  _:_\*    Slowness IV     _:_\*    Nausea  _:_\*    Nausea  _:_\*    Regeneration II     1:00

**Comment by LightningThunda** [comment]
how do you coat a weapon/tool in the first place?

**Comment by YaYa7979** [comment]
You have to put both the compound and the weapon/tool into a crafting grid (Inventory or workbench).

NOTE: This does not work for all chemicals.

Also, here is a list of many more compound effects: http://pastebin.com/download.php?i=4vh0k24z

**Comment by jakimfett** [comment]
@LightningThunda and @YaYa7979:
The Minechem bug tracker is now on my fork of the project, you can find it [here](https://github.com/jakimfett/Minechem/issues).

# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
