### ISSUE TITLE
Food and Stuff laced with molecules missing tooltip info.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [AdlyTempleton/MineChem#154]
All the food and pills that are laced with molecules, like for instance testosterone are missing some sort of information in the tooltip what they've been laced with.

**Comment by jakimfett** [comment]
This is actually intentional. 
![](http://pics.jakimfett.com/14-4-14_17:31:05.png)

At some point in the future, I may add functionality to the microscope to allow this to be "discovered" somehow.
