### ISSUE TITLE
Can't apply elements to polytool.

### ISSUE THREAD

**Issue by webmilio** [AdlyTempleton/MineChem#156]
I've searched for this issue in the closed issues and open ones, and I couldn't find it. I apologize in advance if it already exists.

It seems I can apply some elements perfectly fine (like Carbon), but can't apply others (like Helium and Silicon). I already applied Carbon when I tried applying Silicon. I made a new Polytool and tried applying Helium, but it didn't work.

**Comment by jakimfett** [comment]
I loaded up the most recent version, and it [appears that it's working](http://pics.jakimfett.com/14-4-14_17:13:57.png). What version of Minechem are you using?

I'm going to go ahead and close this issue, if you can provide steps to reproduce it in the [newest Minechem build from CurseForge](http://minecraft.curseforge.com/mc-mods/minechem-5/) I'll re-open this.
