### ISSUE TITLE
Blaze Rod duplication

### ISSUE THREAD

**Issue by iderickson** [AdlyTempleton/MineChem#158]
Step 1) put a blaze rod in the chemical decomposer, and you get 7 Pu

Step 2) Using the Chemical Synthesis Machine, craft 2 blaze rods from 6 of the Pu.

You have now made 2 blaze rods plus one blaze powder from a single blaze rod.

**Comment by MFernflower** [comment]
Thanks,  A fix is now in the works.

**Comment by jakimfett** [comment]
Fixed in the upcoming dev build. Thanks for the report!
