### ISSUE TITLE
Redstone Torch in Decomposer

### ISSUE THREAD

**Issue by CocoaMix86** [AdlyTempleton/MineChem#159]
placing redstone torches in the decomposer (while in the newset DEV build) causes the game to crash (and might have corrupted my world).

**Comment by CocoaMix86** [comment]
Don't worry about my corrupted world. It was just a superflat world for testing random things

**Comment by Maxwolf** [comment]
Same thing I can report putting wooden shovel inside the decomposer will cause' the same crash with Decomposer. http://pastebin.com/1Kb54ieH

**Comment by jakimfett** [comment]
Fixed in the next dev version.
