### ISSUE TITLE
Chemical Storage chest double-chest bug

### ISSUE THREAD

**Issue by Maxwolf** [AdlyTempleton/MineChem#161]
If you attempt to place a chemical chest next to a normal wooden chest the vanilla check that tries to make it into a double-chest freaks out and you end up with invisible chests.

Putting a block of space between chemical chest and the normal chest will prevent this problem, the bug only occurs when placing chemical chest directly next to a normal chest.

![screenshot 2014-04-22 22 31 07](https://cloud.githubusercontent.com/assets/6830398/2773858/8076804e-caa8-11e3-84a1-9cce0121c5c7.png)

**Comment by BBoldt** [comment]
![](http://i.imgur.com/noJg1yT.jpg)
This can happen too, just try placing regular chests in various configurations around the chemical chest.

**Comment by jakimfett** [comment]
Fixed this by adding the Leaded Chest. Chemical storage chests will be unplacable in 5.0.5-Dev5 and later, however they can still be picked up, and once picked up, can be crafted into Leaded Chests.
