### ISSUE TITLE
Chemical Bombs

### ISSUE THREAD

**Issue by CocoaMix86** [AdlyTempleton/MineChem#162]
something that would be be cool would be a special crafting table allowing you to craft bombs out of certain elements and they all do different things. Just an idea.

**Comment by MFernflower** [comment]
Like splash potions of various molecules and some elements? Sounds like a cool idea. I like it alot. I could add all sorts of evil like protein cross linkers like phosgene and formaldehyde and alkylating mustards.

**Comment by CocoaMix86** [comment]
Sort of i guess. Like helium bomb would make things float. Uranium bomb
makes thing get like poison or wither of a high level. Lead bomb makes it
almost impossible to jump. All sorts

**Comment by jakimfett** [comment]
I'm going to add something similar to this in either the 5.1.x or 5.2.x release, when I integrate Alchemy++ support.
