### ISSUE TITLE
Radioactive elements shouldn't degrade inside machines

### ISSUE THREAD

**Issue by drakray** [AdlyTempleton/MineChem#163]
Make the machine inventory not deomposing radioactive element, and add a pipe to allow transport of radioactive stuff
Thermal Expansion ItemDuct are already made with Lead, maybe they could transport readioactive stuff without degradation?
this way we could move stuff around in Science Complex

**Comment by jakimfett** [comment]
Any chance you could elaborate on this a bit? If I understand correctly, you want the decomposer to...well...not decompose, but instead do something else?

**Comment by drakray** [comment]
sorry that wasn't clear lol
I think the output inventory of the Decomposer and of the Chemical Synthesis Machine should not degrade the radioactive element
for example, if you decompose many block of Uranium, the delay in decomposing create multiple stack of U that doesn't have the same NBT value, so they won't stack
this become quickly a real pain to manage, even with Impulse Itemduct to quickly remove the element from the Decomposer to the Lead Chest

**Comment by jakimfett** [comment]
Ah, that makes more sense. I'll see what I can do, but I can't necessarily say how I'll do it. 

We've been talking about splitting the decomposition process up into various methods of decomposition (for a slightly more realistic feel), such as heat or acid. But that won't show up until at the very least 5.1.x, if not later.

**Comment by drakray** [comment]
it's ok, take your time and make it good :)
just a quick question, are you still modding for 1.6.4?
I really hope so, in my opinion there is nothing good in 1.7.x givin  the proximity of 1.8, and all the nice mods are 1.6.4, so I really hope to see these great feature and optimization in 1.6.4 :)

**Comment by jakimfett** [comment]
Yes, and I'll be modding for 1.6.4 until 1.7 is a lot more stable. And, when I make the move to 1.7, I'll be releasing a final stable version before I make the jump.

**Comment by sunmaz2** [comment]
This feature would be excellent. Thank you for considering it.

**Comment by jakimfett** [comment]
Added this, it'll be in the next dev build.
