### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by sunmaz2** [AdlyTempleton/MineChem#165]
Numerous items can currently be duplicated by crafting a new item from the initial item, decomposing the new item, and re-synthesizing the initial item.

We provide an example of this:

Obtain >=2 white wool -> Craft (3) carpets from the two wool -> Decompose carpets -> Synthesize more wool -> Repeat <i>ad infinitum</i>

**Comment by jakimfett** [comment]
What mod are the carpets from?

**Comment by sunmaz2** [comment]
None. They are vanilla Minecraft items. They are crafted by placing two wool (of any colour) horizontally next to each-other in a crafting grid.

It's also worth mentioning that this is my favourite mod in the entire RR pack -- a <i>very</i> nice job indeed.

**Comment by jakimfett** [comment]
I've got a fix for this now, it'll be in the 5.0.5-Dev4 release. The math is a bit imprecise, so if you repeatedly decompose and then synthesize wool (or carpets), you'll eventually end up with nothing.
