### ISSUE TITLE
Decompser just eats piped in inorganic TiC liquid metals 

### ISSUE THREAD

**Issue by MFernflower** [AdlyTempleton/MineChem#167]
![2014-04-24_20 26 07](https://cloud.githubusercontent.com/assets/3164942/2796499/43945070-cc10-11e3-8260-2d031884b9d9.png)
(Done in a real environment with Minechem-5.0.5-DEV2.jar) 
(Tested with liquid TiC steel)

**Comment by CocoaMix86** [comment]
The Decompsoser does not decompose most liquids except for Water and Resonant Ender (From what I've found)

**Comment by MFernflower** [comment]
Because of some bugs in the code. Alot of them to be exact.

**Comment by jakimfett** [comment]
I'm going to be ripping out the fluids stuff and reworking it to use a different machine, but that won't happen until at least 5.1.x.

I'm going to add this to the known issues list and move on for now.
