### ISSUE TITLE
Alumite ingots (TConstruct) cause decomposer lag

### ISSUE THREAD

**Issue by MFernflower** [AdlyTempleton/MineChem#168]
with no output

**Comment by jakimfett** [comment]
I'm betting this is directly related to #140.

**Comment by jakimfett** [comment]
What mod is alumite from, @MFernflower ?

**Comment by jakimfett** [comment]
Fixed by Maxwolf's changes. 120+ FPS with an Alumite ingot in a decomposer.
![](http://pics.jakimfett.com/14-5-20_18:04:01.png)
