### ISSUE TITLE
Decomposing piped in Water

### ISSUE THREAD

**Issue by CocoaMix86** [AdlyTempleton/MineChem#169]
Piping water into a decomposer results in 1 Hydrogen and 1 Oxygen, instead of the normal 2 Hydrogen and 1 Oxygen you would get from decomposing a Water(item id:4993:1)

**Comment by MFernflower** [comment]
Damn. that's some basic water you got there!

**Comment by CocoaMix86** [comment]
It's technically making a Hydroxide ion. I'd rather drink my dihydrogen monoxide :P

**Comment by MFernflower** [comment]
Hence my joke about high Ph

**Comment by CocoaMix86** [comment]
Ah yes. I'm learning about acids and bases in Chemistry now.

**Comment by jakimfett** [comment]
Yup, definitely a bug. I'll fix this in the next dev release.

**Comment by jakimfett** [comment]
Code committed, it'll be included in the dev3 release.
