### ISSUE TITLE
Jenkins Build Error

### ISSUE THREAD

**Issue by calclavia** [AdlyTempleton/MineChem#17]
Checked Jenkins, you've got build errors and it doesn't seem to be fixed:

src/minecraft/ljdp/minechem/client/render/item/ItemMinechemRenderer.java:14: error: an enum switch case label must be the unqualified name of an enumeration constant
        case EQUIPPED_FIRST_PERSON: stevenk:
             ^

src/minecraft/ljdp/minechem/client/render/item/ItemSynthesisRenderer.java:29: error: an enum switch case label must be the unqualified name of an enumeration constant
        case EQUIPPED_FIRST_PERSON: stevenk:
             ^

src/minecraft/ljdp/minechem/client/render/item/ItemMicroscopeRenderer.java:24: error: an enum switch case label must be the unqualified name of an enumeration constant
        case EQUIPPED_FIRST_PERSON: stevenk:
             ^

src/minecraft/ljdp/minechem/client/render/item/ItemMicroscopeRenderer.java:56: error: an enum switch case label must be the unqualified name of an enumeration constant
        case EQUIPPED_FIRST_PERSON: stevenk:
             ^

src/minecraft/ljdp/minechem/client/render/item/ItemDecomposerRenderer.java:29: error: an enum switch case label must be the unqualified name of an enumeration constant
        case EQUIPPED_FIRST_PERSON: stevenk:
             ^

src/minecraft/ljdp/minechem/client/render/item/ItemBlueprintProjectorRenderer.java:29: error: an enum switch case label must be the unqualified name of an enumeration constant
        case EQUIPPED_FIRST_PERSON: stevenk:
             ^

**Comment by Rushmead** [comment]
Working on it
