### ISSUE TITLE
Resonant Ender decomposer math is off

### ISSUE THREAD

**Issue by CocoaMix86** [AdlyTempleton/MineChem#170]
Ok, in Thermal Expansion, it takes 4 Enderpearls to make 1 bucket of Resonant Ender.
1 Enderpearl decomposes into 8 Calcium Carbonate and 1 Einsteinium.
1 Resonant Ender Bucket decomposes into 48 Calcium Carbonate and 6 Einsteinium.
That's 6 times as much as an ender pearl, where as it should only be 4 times.

Not sure if this is a bug or intended. Just found it odd.
![2014-04-27_17 56 54](https://cloud.githubusercontent.com/assets/5726733/2812522/4b18313a-ce5f-11e3-837d-293fd57044ea.png)

**Comment by jakimfett** [comment]
Thanks, this is definitely a bug. That said, I'm not sure there's an easy fix. I'll try and fix it in the dev3 release, but no promises.

**Comment by jakimfett** [comment]
I added a somewhat hack-y workaround in the code that _should_ work. That said...it may not work at all.
