### ISSUE TITLE
Client wont start

### ISSUE THREAD

**Issue by JasonMcRay** [AdlyTempleton/MineChem#171]
Hi. I wanted to use MineChem in my modpack but I am encountering this problem. My minecraft client just hangs up when starting with the Mojang screen.

ForgeLog (since i have nothing else to show you): http://paste.ee/p/71XtI
Minechem: 5.0.5 dev2 (also tried with 5.0.4, same problem)

Thats all. It just hangs like that forever. I need to forcekill it... :(

**Comment by ruyanve** [comment]
Check your block ID's! This should be a simple ID confilct!

**Comment by jakimfett** [comment]
Minechem has not been tested with Java 8. Please use Java 7, and try again. If you still have the issue, please re-open this ticket.
