### ISSUE TITLE
Decomposer/Synthesis blacklist

### ISSUE THREAD

**Issue by BBoldt** [AdlyTempleton/MineChem#172]
It would be a nice feature to be able to blacklist certain items/blocks/liquids from being decomposed or synthesized.

When putting together a modpack, there might be some things you want players to produce in a way not involving minechem. 

Also, sometimes there are things that you may not want being broken down. 

Example: Color mods from nhave's omniwrench drop from mobs but also have a recipe which involves quartz, iron, and dye, so a simple mob farm can result in all of this from each item:
![](http://i.imgur.com/lQBjhcB.png)

I wouldn't expect you to make compatibility for every mod that does something like that, so I think a blacklist would probably be best.

**Comment by jakimfett** [comment]
This is a good idea. Probably won't happen until 5.0.6 (or possibly even 5.1.x), as 5.0.5 is all about cleaning up the bugs, but I can almost guarantee that a blacklist (and possibly also a whitelist) of some sort will be implemented.

Will be highly configurable, eg:

```
UseDecomposerBlacklist=true/false
UseDecomposerBlacklistAsWhitelist=true/false
DecomposerBlacklist {
    'cobblestone',
    'uranium'
}
UseSynthesizerBlacklist=true/false
UseSynthesizerBlacklistAsWhitelist=true/false
SynthesizerBlacklist {
    'diamond',
    'enderpearl',
    'wool',
}
```

**Comment by CocoaMix86** [comment]
So a whitle/black list will be in a config file, not a thing like a Thermal Expansion pneumatic servos do for pipes.

**Comment by jakimfett** [comment]
Yes. This is a server admin thing to address server specific balance issues, not a player thing. 

For item sorting, use thermal expansion or one of the other dozen mods that add sorting of some form.

**Comment by jakimfett** [comment]
Moved over to the root repository issues list as an enhancement. Closing.

https://github.com/jakimfett/MineChem/issues/16
