### ISSUE TITLE
Element names not getting localized

### ISSUE THREAD

**Issue by Jona123** [AdlyTempleton/MineChem#173]
So, the element tubes (what are they actually called?!) show very weird names when you hover over them, but the blocks are just fine. See the screenshots for more info:
http://prntscr.com/3eng60
http://prntscr.com/3eng60
The names are all formatted like this: 
MineChem.element.(element letter)
OR
minechem.molecule.(moleculename)

**Comment by CocoaMix86** [comment]
All my elements are fine for names and so are nearly all the molecules. Only 5 had funny names like you reported.
![2014-04-29_16 22 09](https://cloud.githubusercontent.com/assets/5726733/2835056/7a8c56d6-cfe4-11e3-96e9-17172d216fbe.png)
![2014-04-29_16 22 10](https://cloud.githubusercontent.com/assets/5726733/2835057/7a9311a6-cfe4-11e3-9ab7-3ffaaf283c61.png)
![2014-04-29_16 22 11](https://cloud.githubusercontent.com/assets/5726733/2835058/7a999170-cfe4-11e3-9eee-6e1973877087.png)
![2014-04-29_16 22 12](https://cloud.githubusercontent.com/assets/5726733/2835059/7a9fbf1e-cfe4-11e3-9017-d8a069404773.png)
![2014-04-29_16 22 13](https://cloud.githubusercontent.com/assets/5726733/2835060/7aa749b4-cfe4-11e3-87cc-be0a57c5cf94.png)

**Comment by MFernflower** [comment]
The language files are old and need to be updated.  Thanks for reminding
me!

**Comment by MFernflower** [comment]
See #175

**Comment by jakimfett** [comment]
Will be fixed in 5.0.5-Dev4.
