### ISSUE TITLE
Microscope bugs, showing strange/random results for some items & overflow

### ISSUE THREAD

**Issue by Bourne-ID** [AdlyTempleton/MineChem#176]
Placing a Chemical Decomposer, Chemical Synthesis machine and other advanced items into the microscope on decompose mode makes it go a little crazy, with random tubes changing per tick. Also any items that have more than 9 elements/components etc. causes a flood into the players inventory (although this resets back to normal on a refresh of any kind). Example attached.
![output_maragq](https://cloud.githubusercontent.com/assets/7073616/2855288/db4dd7b6-d15a-11e3-8c10-1474032f1b94.gif)

**Comment by jakimfett** [comment]
Fixed by Maxwolf's refactor. The decomposer recipes now only iterate through a few times, rather than hundreds of times. Download Minechem 5.0.5-Dev5 to get the fix.
![](http://pics.jakimfett.com/14-5-21_18:52:58.png)
