### ISSUE TITLE
[3.x.115] Bad mcmod.info file preventing mod from loading.

### ISSUE THREAD

**Issue by Timeslice42** [AdlyTempleton/MineChem#18]
The new mcmod.info file in #115 was written incorrectly, causing the mod to fail to load.

Here is the corrected file: http://pastebin.com/1emjhPAE

Fixed formatting.
Fixed credits value being in the mcversion field.
Fixed authors value not being in an array (this is what broke loading).

**Comment by MFernflower** [comment]
I think rushmead fixed it however...
