### ISSUE TITLE
Blaze Rod/Plutonium ratio incorrect

### ISSUE THREAD

**Issue by Bourne-ID** [AdlyTempleton/MineChem#180]
1 blaze rod decomposes to 7 plutonium, but only requires 3 plutonium to synthesize. As such a user only needs to obtain 1 blaze rod to get infinite blaze rods.

**Comment by jakimfett** [comment]
What version of Minechem are you using? I fixed this in (I believe) 5.0.5-Dev1, and the current version is 5.0.5-Dev3

**Comment by Bourne-ID** [comment]
My bad - 5.0.4 but I did check the source code in this repository. I didn't
realise this was a fork project given the number of issues raised -
apologies.

Should future issues be raised against the root project instead of this
fork (after making sure I'm on the latest release)?

**Comment by jakimfett** [comment]
The project is in transition right now. Pixlepix is transferring the project over to me, but for now I'm still tracking issues on his fork (now that my repo is root).

For now, go ahead and keep reporting issues here. Once I finish squashing all the bugs reported here, I'll make the switch over.

**Comment by Bourne-ID** [comment]
understood, thanks. Closing.
