### ISSUE TITLE
Resonant Ender decomposition numbers incorrect

### ISSUE THREAD

**Issue by CocoaMix86** [AdlyTempleton/MineChem#181]
Minechem 5.0.5-Dev3 still has the wrong Resonant Ender math.

In Thermal Expansion, it takes 4 Enderpearls to make 1 bucket of Resonant Ender.
1 Enderpearl decomposes into 8 Calcium Carbonate and 1 Einsteinium.
1 Resonant Ender Bucket decomposes into 48 Calcium Carbonate and 6 Einsteinium.
That's 6 times as much as an ender pearl, where as it should only be 4 times.

![](https://cloud.githubusercontent.com/assets/5726733/2812522/4b18313a-ce5f-11e3-837d-293fd57044ea.png)

**Comment by jakimfett** [comment]
Whoops, looks like I set the fluid to be balanced, but I did it the wrong way, and then didn't actually use the new variable. The (upcoming) 5.0.5-Dev4 release should fix this.
