### ISSUE TITLE
Cannot finish construct chambers

### ISSUE THREAD

**Issue by AndaleTheGreat** [AdlyTempleton/MineChem#182]
Bought the 5x5x5 reactor plan, put into projector. Filled in the walls as they appeared but once I get to the 3rd or 4th wall there is always a single block missing in the projection. Since there's no projection block I cannot place the wall pieces.  I can post pics or vids if requested. I hate to post about it but I've not found a link yet to anyone with a similar issue.

Playing in the FTB Lapito's Pack

**Comment by jakimfett** [comment]
If you could post a screenshot of it, I'd greatly appreciate it. Also, you might check to see if the Lapito pack is using the latest build of the mod, as the 5.0.5 builds have a lot of bugfixes.

**Comment by AndaleTheGreat** [comment]
Updated the pack from 502 to 504 when testing (did not try the developer build since those are not always stable). Tried again and grabbed the pic's.
The projector with the 5x: 
![http://imgur.com/CYaiKgN](https://i.imgur.com/CYaiKgN.png)
The build: 
![http://imgur.com/PIkc3oj](http://imgur.com/PIkc3oj.png)
Will do a backup and swap for the 505 build tomorrow.

**Comment by jakimfett** [comment]
Definitely go ahead and get the 5.0.5-Dev3 (or Dev4 if I get around to releasing it by then...) as the only changes I've made are bugfixes, so it's currently a lot more stable than the 5.0.4 versions.

This probably won't continue to be true in the future, but the 5.0.5 version is completely bugfixes, there will be no enhancements.

**Comment by AndaleTheGreat** [comment]
Moved to Dev3, still doing it, but I've realized it may be doing it because I was standing too close. Originally it seemed a bit more random, now it seems to do it only where I am near.
I'm more surprised it doesn't get fixed by removing the schematic.

I tried making sure I did not step into the area as I was building it. I placed all blocks from as far as possible and it finally worked, although two of the ghost blocks did not appear I was still able to place where they should have been.

**Comment by jakimfett** [comment]
Interesting...does it have this problem when you don't have any other mods installed?

UPDATE: I've tested this a couple of different ways, but haven't been able to reproduce the issue. Could you provide a list of mods that you're running? I'm wondering if there's something interfering with it.

**Comment by jakimfett** [comment]
@AndaleTheGreat - I've been unable to reproduce this issue. Can you point me to either a list of the mods you're using, or where I can download the pack you're using? If I can't reproduce it, I can't fix it.

**Comment by jakimfett** [comment]
I've been unable to reproduce this. If you can reproduce this with the latest dev build, go ahead and re-open the ticket.

**Comment by Maxwolf** [comment]
I noticed this bug while messing with them. It occurs if you miss any clicking with the blocks at all, you have to get every single one correct or it will not render the next layer correctly. They are still there and you can actually place a block and break it and the ghost reference block will reappear, this might be an issue where we need to send some more information to the client or possibly render the entire machine as ghost blocks, or even let the blueprint machine build the structure for you.

If all else fails a possible redo on these blocks to make them tile entities instead that way they could still be used as intended.
