### ISSUE TITLE
Shift Click Decomposer ignores first 4 (top left) inventory slots

### ISSUE THREAD

**Issue by Bourne-ID** [AdlyTempleton/MineChem#183]
If you have an almost full inventory but leave the 4 top-left slots empty and shift click (move stack) on a decomposed element/etc, it will not move into the final 4 empty slots. Gaps/stacking elsewhere fills as expected. 

There's also a potential of item loss whilst shift clicking, but I am still trying to nail the exact cause of the issue. Screenshots available on request, and I'll try and narrow down the cause tonight.

**Comment by jakimfett** [comment]
Thanks for the report, I'll take a look at it. Does the shift clicking issue seem to effect all machines, or just specific ones?

Also, if/when you figure out what's up with losing items while shift clicking, could you open a new ticket for that one?

**Comment by Bourne-ID** [comment]
Both the synthesis and decomposer. Items are lost when inventory is full
and shift clicking on the Synthesis output only. (decomposer doesn't appear
to do an action when inventory is full)

**Comment by jakimfett** [comment]
Thanks, could you open a separate ticket for the losing items one?

**Comment by jakimfett** [comment]
Confirmed this in my dev environment. I'll try and fix this for the next dev release.

**Comment by jakimfett** [comment]
This will be fixed in the next dev build (Minechem 5.0.5-Dev6)
