### ISSUE TITLE
Most machines have purple breaking particles

### ISSUE THREAD

**Issue by jakimfett** [AdlyTempleton/MineChem#184]
When most of the machines are broken, the particles are purpleish, and have the texture not found pattern.
![](http://pics.jakimfett.com/14-5-12_15:16:36.png)
The decomposer is not effected by this:
![](http://pics.jakimfett.com/14-5-12_15:18:20.png)

**Comment by CocoaMix86** [comment]
I can confirm this as well.
![2014-05-12_20 01 54](https://cloud.githubusercontent.com/assets/5726733/2952406/3ea3d99a-da3a-11e3-973e-5e3a029a18a1.png)

**Comment by jakimfett** [comment]
Fixed by Maxwolf's changes. Closing.
