### ISSUE TITLE
Item Loss on shift-click Synthesis output with full inventory

### ISSUE THREAD

**Issue by Bourne-ID** [AdlyTempleton/MineChem#185]
When the inventory is full and you shift-click the output of the Systhesis machine (IE to move the stack to the inventory), it removes the stack from the systhesis machine but as there is no space in the inventory, it disappears (and doesn't pop out on the floor).

**Comment by jakimfett** [comment]
This will be fixed in the next dev build (Minechem 5.0.5-Dev6)
