### ISSUE TITLE
Buildcraft pipes don't connect

### ISSUE THREAD

**Issue by Turakar** [AdlyTempleton/MineChem#187]
If I place a kinesis pipe (tested with golden ones) next to a MineChem machine (tested with Chrmical Decomposer and the other one which requires power), they don't connect and are also not transferrimg power. I'm running the latest stable Buildcraft and Minechem version.

**Comment by CocoaMix86** [comment]
Minechem machines only accept Redstone Flux, which is part of Thermal Expansion

**Comment by Turakar** [comment]
Oh ok, I thought they would also conect to bc pipes. Well, then this changes to a feature request.

**Comment by Bourne-ID** [comment]
Have you tried universal pipes (if you have the relevant mod?)

**Comment by Turakar** [comment]
I don't know Universal Pipes (and can't find it), but I would anyway suggest to add a as big as possible support of the different energy systems. However this is more a thing to do after the bug fixes.

**Comment by jakimfett** [comment]
I'm adding this as a [feature request](https://github.com/jakimfett/MineChem/issues/17) in the main repo, and closing the issue. Thanks for bringing it to my attention!
