### ISSUE TITLE
Chemical Decomposer calculations for NEI often very time intensive

### ISSUE THREAD

**Issue by nekojess** [AdlyTempleton/MineChem#188]
Admittedly, my computer isn't very powerful, so this might not be an issue on better computers. 

I'm using the [Yogscast Complete Pack](http://www.atlauncher.com/pack/YogscastCompletePack/) on the ATLauncher launcher, so there's quite a few other mods installed. I noticed my NEI was slow to look up Usage recipes, so I enabled the usage profiling (Inventory -> Profile Recipes) in the NEI settings and immediately noticed that the Chemical Decomposer was consistently high on the list.

Both my friend and I then searched for Machinist's Workbench (just as an example) and hit the hotkey to show Usage. My computer took 35 seconds (which I said before isn't very good), and their computer took nearly 3 seconds.

![chem_decomposer_time_machinists_workbench_1](https://cloud.githubusercontent.com/assets/790271/2963034/ba52ce9c-dad6-11e3-9ecb-ec14b9be7a46.png)
![chem_decomposer_time_machinists_workbench_2](https://cloud.githubusercontent.com/assets/790271/2963033/ba4b0234-dad6-11e3-99da-2e657c1753bc.png)

Searching for the Usage of Iron Tank Valve from Railcraft actually completely locked up both of our Minecrafts, forcing us to kill them and start again. Of course the profiler times never showed up, but I'm pretty confident it's the same issue.

Thanks.

**Comment by Bourne-ID** [comment]
I've duplicated the issue with iron tank wall in issue #189 (submitted and then read this). Faster machines will have less usage time, but the more complex the recipe the longer it takes, some items produce a noticeable pause.

**Comment by jakimfett** [comment]
With the changes Maxwolf made, the usage is at a much more reasonable level now. Thanks for reporting this!
![](http://pics.jakimfett.com/14-5-20_23:49:45.png)
