### ISSUE TITLE
NEI: Client Freeze & Server Crash with railcraft ID 452: Iron Tank Wall. (NEI usage & Decomposer)

### ISSUE THREAD

**Issue by Bourne-ID** [AdlyTempleton/MineChem#189]
_Client_
The minecraft client freezes when using the NEI usage tool (U on item) on railcraft block ID 452: Iron Tank Wall. DecomposerRecipeHandler appears to struggle to work out the decompose elements for this block, where the recipe's components are 8x ID452 (Iron Tank Wall) and 1x ID351 (vanilla dye's).

_Server_
When placed in a decomposer, I believe the server is running the same calculation as the client, therefore causing the server to crash with the 60 second no-tick. Logs are located here: https://dl.dropboxusercontent.com/u/35695242/server.log - Please note the server had to be restored to resolve the issue (although anyone attempting to decompose an iron tank wall is probably trolling anyway...)

_Mods used_ 
Forge 964
CodeChicken 0.9.0.9
NEI 1.6.1.9
MineChem DEV3
Railcraft 8.4.0.0

_Debugging Thoughts_
I believe this is caused by the CraftingManager.getInstance().getRecipeList() For loop inside the DecomposerRecipeHandler.getRecipe() recursive method, where the for loop is being is iterating through insane number of times. 

After playing with the level condition (line 36), I found the following:

Level 1, the for loop is iterating 1404 times
Level 2, the iteration count is 186732 
Level 3: ~24 Million (takes time to complete)
My estimates is level 5 (in code) with this recipe is being called 48 trillion times... ((2^5)^7)*1404)

The client thread dump is roughly the same as the stacktrace in the server.log file above, but available if requested. 

More info on request.

**Comment by jakimfett** [comment]
After Maxwolf's changes, the lag issue seems to be resolved (note the FPS in my screenshot below). I'm going to leave this open until you get a chance to check the next dev build, @Bourne-ID 
![](http://pics.jakimfett.com/14-5-20_18:24:27.png)

**Comment by jakimfett** [comment]
After talking with Maxwolf, it looks like he made a bunch of changes to resolve this. Closing.

**Comment by Bourne-ID** [comment]
Looks good, like the code change and impressed by the refactoring. Thanks
for fixing.

**Comment by Maxwolf** [comment]
You are very welcome :>
