### ISSUE TITLE
[3.x.115] Chemical Synthesizer Has Wrong Max Energy Storage.

### ISSUE THREAD

**Issue by Timeslice42** [AdlyTempleton/MineChem#19]
The chemical synthesizer has the wrong value for maximum energy storage. It is supposed to have a maximum storage of 900000, but it only has 10000.

The energy costs for synthesizing were designed for this value, and setting it to 10000 prevents several important recipes from being craftable.

**Comment by MFernflower** [comment]
Fixed it. Changed it to 922220
