### ISSUE TITLE
All base elements named "Unnamed"

### ISSUE THREAD

**Issue by ghost** [AdlyTempleton/MineChem#192]
All the base elements appear to be named "Unnamed" in the inventory screen and NEI. 
Selecting the elements in the hotbar while not in the inventory screen displays their proper name.

MineChem: 5.0.5 Dev5

**Comment by Maxwolf** [comment]
Ah this might be the way the items internally reference their name. Perhaps there is a way we can feed out the correct name so NEI will realize this.

**Comment by ghost** [comment]
I just disabled NEI and mousing over a base element now results in a crash.
Selecting them in the hotbar was still fine though.

FML Log: http://pastebin.com/tfp4TWzm

**Comment by jakimfett** [comment]
@xRevan117x could you post a screenshot? 

I can see the names both in NEI...
![](http://pics.jakimfett.com/14-5-21_18:42:10.png)
...and in my inventory.
![](http://pics.jakimfett.com/14-5-21_18:42:58.png)

**Comment by ghost** [comment]
Sure. I just also realized that i'm not seeing any descriptors either.

![minechem](https://cloud.githubusercontent.com/assets/7663102/3048994/7ce42442-e153-11e3-9842-fd1b0192f499.png)

![minechem2](https://cloud.githubusercontent.com/assets/7663102/3048996/8610302e-e153-11e3-9a60-6405d3ad4abd.png)

![minechem3](https://cloud.githubusercontent.com/assets/7663102/3048997/8a0dec02-e153-11e3-9ecd-f6c9a5e42d0b.png)

**Comment by jakimfett** [comment]
Could I get you to re-download Minechem? This may sound silly, but your log file indicates you might have gotten a corrupted jar file. 
![](http://pics.jakimfett.com/14-5-21_19:01:00.png)

Go ahead and download [build 54 from Jenkins](http://mc.picraft.com/build/job/Minechem/54/).

**Comment by ghost** [comment]
That did it. Everything is working properly now. Thanks, I should probably do more than just glance over the log in the future.

**Comment by jakimfett** [comment]
Yup, logs have info in them for a reason!
