### ISSUE TITLE
no energy is working

### ISSUE THREAD

**Issue by 6P14y3r** [AdlyTempleton/MineChem#193]
the machines doesn't work with any sort of cable/energy source =(

i tried everything from Thermal Expansions, Buildcraft and Mekanism
(there is no error in the log)

using  "MineChem-5.0.5-Dev5"
i don't know if it worked in earlier versions

edit: 
working in "Minechem-5.0.4" with everything (Thermal Expansions, Buildcraft and Mekanism)

**Comment by jakimfett** [comment]
You need to download the [Universal Electricity core](http://universalelectricity.com/downloads/). I forgot to mention that in the changelogs, I'll add that right now.

**Comment by 6P14y3r** [comment]
thanks for the quick reply, everything is working perfectly again :)

**Comment by jakimfett** [comment]
No problem, you caught me at a good time. Enjoy the mod!
