### ISSUE TITLE
Crash when exposing chemical decomposer to thermal expansion conduit

### ISSUE THREAD

**Issue by BrandonBrowning** [AdlyTempleton/MineChem#195]
Connected a chemical decomposer's back to a thermal expansion leadstone energy conduit, with a chest under the decomposer.  Game immediately crashed immediately and then again every time I load the world.  Also happens with thermal expansion leadstone energy cell, and dynamos directly.

Modpack is ftb monster - a few mods + minechem.

Trace at http://pastebin.com/5qY4AJYK

I'll post more if I can find a better repro case.  Let me know if you need any other info.

**Comment by BrandonBrowning** [comment]
This does not appear to happen in ftb direwolf20 + minechem.

I apologize if the issue is odd! :)

**Comment by Maxwolf** [comment]
This is caused by using an old version of UE. Please update to 3.1x or higher!

**Comment by BrandonBrowning** [comment]
:+1: :heart:
