### ISSUE TITLE
craft bug about Cr in gregtech 

### ISSUE THREAD

**Issue by fjq12596** [AdlyTempleton/MineChem#196]
I found that Cr dust is crafted by 16 Al,I love this mod and I hope this bug would be fixed,谢谢:)

**Comment by fjq12596** [comment]
and aluminum dust(gt) can not be craft.In old vision(mc1.52)Cr dust is crafted by 16 Cr.

**Comment by jakimfett** [comment]
I'm a bit unclear as to what the actual bug is. Are you trying to synthesize Cr, and the recipe no longer works? What version of the mod are you using? What version of Minecraft? Can you provide a screenshot of the problem?

**Comment by fjq12596** [comment]
The version I use is minecraft1.64,minechem5.0.3.I mean a recipe itself is wrong . Chromium dust (gregtech) is crafted by 16 aluminium,it should be crafted by 16 chromium,not 16 aluminium.

**Comment by jakimfett** [comment]
Ah, that makes much more sense. I'll take a look and see if that is still an issue. You're several versions behind, so please update. If the issue still exists in Minechem 5.0.5-Dev5, I'll see if I can fix that for the next version.

**Comment by jakimfett** [comment]
@fjq12596 After the refactor of the decomposer and synthesis mechanics, Gregtech Chrome no longer has a synthesis or a decomposer recipe.
![](http://pics.jakimfett.com/2014-06-01_23-53-46.png)
