### ISSUE TITLE
Crash when connecting itemducts to reactor

### ISSUE THREAD

**Issue by CoryManson** [AdlyTempleton/MineChem#197]
Hi guys, as discussed in IRC:

Region file: https://dl.dropboxusercontent.com/u/82904851/r.-4.-2.mca

Coords: -1830 70 -744

Crash: http://pastebin.com/c7Us7sqp

Occurred when connecting reactor to a diamond chest via TE3 Itemducts

**Comment by jakimfett** [comment]
This will be fixed in the next dev build (Minechem 5.0.5-Dev6)
