### ISSUE TITLE
Dupe between Steves Factory Manager and Minechem

### ISSUE THREAD

**Issue by CoryManson** [AdlyTempleton/MineChem#198]
Reported by one of my players via RR Support forums:

Explanation:
http://i.imgur.com/FUZK79g.png

Setup:
http://i.imgur.com/aH0zdKt.png
http://i.imgur.com/TVkesli.png
http://i.imgur.com/7HOV6QV.png
http://i.imgur.com/rUXnA4d.png

**Comment by jakimfett** [comment]
Looks like this is related to #149, I'll see if we can get this fixed for the next dev release. No promises though, I haven't messed with SFM ever.

**Comment by jakimfett** [comment]
Fixed this in dev, it'll show up in the next release. Thanks for reporting this!
