### ISSUE TITLE
Synthesizer processing time exceptionally high

### ISSUE THREAD

**Issue by Euius** [AdlyTempleton/MineChem#199]
In SMP, the Synthesizer machine uses a lot of processing time checking for redstone status when it's in the "waiting" state. See checkRedstonePower in [TileEntityRedstone](https://github.com/jakimfett/MineChem/blob/master/src/main/java/minechem/tileentity/prefab/MinechemTileEntityRedstone.java#L13)

Minecraft version: 1.6.4
Minechem version: 5.0.5-Dev5

How to reproduce:
Using the [Warmroast profiling tool](http://www.sk89q.com/2013/06/easy-jvm-cpu-profiling-with-warmroast/), place down a synthesizer. Here's a screenshot of what happens: ![](http://i.imgur.com/kP2sSRH.png)

**Comment by Maxwolf** [comment]
Looking into this, I think we can remove this entire class without fear since Minechem does not make use of redstone in any way. These prefabs are from my other mod Mad Science and I used them during my rewrite.

In total a simple fix that should give you some nice gains :)

**Comment by jakimfett** [comment]
This should be fixed in the next dev build. If you need it before I release that, you can get [build #65 from Jenkins](http://mc.picraft.com/build/job/Minechem/65/).
