### ISSUE TITLE
Bug in syntesizer recipes!

### ISSUE THREAD

**Issue by anishin** [AdlyTempleton/MineChem#200]
I find bug in synthesizer recipe in MineChem 5.0.5-Dev1-Dev6 and RC1. In this versions of mod players can craft Chrome dust and ingots (very expensive material, end-game resource) from Aluminium atom (very cheap material, that can be finded as ore). 

I find this bug, when use MineChem with these mods:
IC2Exp (2.0.397)
GregTech (4.08s)
LevelStorage (1.2.3-rc1)
Galacticraft (2.0.13-1063)
TiConstruct (1.5.5.7)

Please, fix this bug (crafting expensive Chrome from cheap Aluminium). 

P. S. Sorry for my English. I'm from Russia.
P. P. S. I LOVE THIS MOD!

**Comment by jakimfett** [comment]
I'll take a poke at this, but that said...GregTech breaks things. In some cases, it breaks things horribly. I can't promise anything will get fixed.

**Comment by anishin** [comment]
I see this bug with and WITHOUT GregTech (with LevelStorage, for exaple). This bug is not ONLY with GregTech. 
P. S. Thank for your work!

**Comment by jakimfett** [comment]
Odd. So this effects any mod that adds Chrome?

**Comment by anishin** [comment]
Yes. RotaryCraft adds Chrome ingot. And I find sinthesizer recipe Aluminium (atom) to Chrome (ingot from RotaryCraft). But after this recipe I find recipe Aluminium (atom) to Aluminium ingot from RotaryCraft... (2 recipes with conflict)

**Comment by anishin** [comment]
In MineChem 5.0.5-RC2 this bug remained (with RotaryCraft, for example). But why did you remove GT compatibility? With GregTech only ONE recipe was wrong (Aluminum element -> Chrome dust/ingot). Please, turn back GT compatibility!
P. S. Sorry for my English.

**Comment by jakimfett** [comment]
@anishin - Gregtech compatibility was not intentionally removed. 

In the process of fixing bugs for version 5.0.5, we refactored the decomposition process to be less CPU intensive. Gregtech recipes are very complex, and the new process doesn't iterate through them completely, resulting in them not being added. It was a performance decision, not something that specifically targets Gregtech.

That being said...if you're playing Gregtech, in general, expect things to be broken.

**Comment by jakimfett** [comment]
Closing this issue to clean up the issue tracker. See https://github.com/jakimfett/MineChem/issues/67 for the enhancement request related to this.
