### ISSUE TITLE
Can't acquire polytool or pills

### ISSUE THREAD

**Issue by Gyramuur** [AdlyTempleton/MineChem#201]
Hi, I'm new here so I have no idea if I'm doing this right or not (probably not), but I'm having an issue where both the polytool and the pills don't show up in NEI, though everything else does and works fine. Trying to manually give myself the items using the item IDs doesn't work, as it tells me there is no such item with that ID. I'm using 5.0.4 and I directly upgraded from 4.3.1-43. I tried deleting the old config and generating a new one, but doing so causes the game to freeze at load with this crash-log:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 6/6/14 8:02 AM
Description: Exception in server tick loop

java.lang.AbstractMethodError: minechem.tileentity.decomposer.DecomposerTileEntity.canConnect(Lnet/minecraftforge/common/ForgeDirection;)Z
    at universalelectricity.core.asm.template.tile.StaticTileForwarder.canConnect(StaticTileForwarder.java:103)
    at minechem.tileentity.prefab.MinechemTileEntity.acceptsEnergyFrom(MinechemTileEntity.java:65)
    at ic2.core.energy.EnergyNetLocal.addTileToGrids(EnergyNetLocal.java:331)
    at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:119)
    at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:26)
    at net.minecraftforge.event.ASMEventHandler_22_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at universalelectricity.core.net.NetworkTickHandler.tickEnd(NetworkTickHandler.java:96)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:622)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1406679696 bytes (1341 MB) / 2878799872 bytes (2745 MB) up to 7635533824 bytes (7281 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 1 loaded mod(s)
          - MAtmos version r26 for 1.6.4
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -XX:MaxPermSize=256m
    AABB Pool Size: 5367 (300552 bytes; 0 MB) allocated, 5367 (300552 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 108 mods loaded, 108 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.7} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PCLCoreModASM{1.0} [PCLCoreModASM](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.8} [Not Enough Items](NotEnoughItems 1.6.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    battlegear2{1.0.5.3} [Mine & Blade Battlegear 2 - Bullseye](1.6.4-MB_Battlegear2-Bullseye-1.0.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{v5.3(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.6.4.r09} [Treecapitator]([1.6.4]TreeCapitator.Forge.1.6.4.r09.Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.0.377-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.377-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedMachines{1.0.6} [IC2 Advanced Machines Addon](AdvancedMachines_exp_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    arsmagica2{1.1.2b} [Ars Magica 2](AM2_1.1.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    antiqueatlas{3.0.10} [Antique Atlas](antiqueatlas-3.0.10-mc1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Autoutils{1.0.1} [Autoutils](autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.26.29} [Backpack](backpack-1.26.29-1.6.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterDungeons{2.4} [Chocolate quest](BetterDungeons207.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.5.5} [BiblioCraft](BiblioCraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{1.2.1} [Biomes O' Plenty](BiomesOPlenty-universal-1.6.4-1.2.1.416.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Additional-Buildcraft-Objects{1.0.7.558} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.7.558.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{v1.9.9} [Carpenter's Blocks](Carpenter's Blocks v1.9.9 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactSolars{4.4.21.306} [Compact Solar Arrays](compactsolars-universal-1.6.4-4.4.21.306.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.58} [ComputerCraft](ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.58} [ComputerCraft Turtles](ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ConfigMod{v1.0} [Extended Mod Config](ConfigMod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoroAI{v1.0} [CoroAI](CoroAI for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CountryGamer_Core{1.1.1} [CountryGamer Core](CountryGamer_Core_1.1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CraftableSaddles{1.0.2} [Craftable Saddles](CraftableSaddles.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DungeonCrawler{0.2.5} [Dungeon Crawler](DungeonCrawler 0.2.5 for MC 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights{1.2.8} [Dynamic Lights](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_onFire{1.0.3} [Dynamic Lights on burning](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_creepers{1.0.3} [Dynamic Lights on Creepers](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_dropItems{1.0.5} [Dynamic Lights on ItemEntities](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_entityClasses{1.0.0} [Dynamic Lights on specified Entities](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_mobEquipment{1.0.3} [Dynamic Lights on Mob Equipment](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights on Flame enchanted Arrows](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_otherPlayers{1.0.5} [Dynamic Lights Other Player Light](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_thePlayer{1.0.9} [Dynamic Lights Player Light](DynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.16.5b} [Enchanting Plus](EnchantingPlus-1.16.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnviroMine{1.1.49} [EnviroMine](EnviroMine-v1.1.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtendedRenderer{v1.0} [Extended Renderer](ExtendedRenderer for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{2.4.0} [iChunUtil](util^iChunUtil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobAmputation{2.0.1} [MobAmputation](files^MobAmputation2.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobDismemberment{2.0.0} [MobDismemberment](files^MobDismemberment2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FlansMod{4.1} [Flans Mod](FlansMod-4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.3.1.0} [Forestry for Minecraft](forestry-A-2.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{2.0.8} [Galacticraft Core](Galacticraft-1.6.4-2.0.8.908.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftMars{2.0.8} [Galacticraft Mars](Galacticraft-Planets-1.6.4-2.0.8.908.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    UniversalElectricity{3.0.1} [Universal Electricity](Universal-Electricity-3.0.1.18-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.227} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.6.X_1.5.2.1} [Tinkers' Construct](TConstruct_mc1.6.4_1.5.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.1.0g} [Thaumcraft](Thaumcraft4.1.0g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HungerOverhaul{1.6.X-2l} [Hunger Overhaul](hungeroverhaul-1.6.X-2l-build3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2NuclearControl{1.6.2e} [Nuclear Control](IC2NuclearControl-1.6.2e-ic2-experimental.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.4.1.702} [Iron Chest](ironchest-universal-1.6.4-5.4.1.702.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LanteaCraft{RC1-33} [LanteaCraft](LanteaCraft-RC1-33.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Lantern{1.63} [Lanterns and Flashlights Mod](Lanterns and Flashlights%281.63%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mca{3.6.1} [Minecraft Comes Alive](MCA-3.6.1 MC-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mekanism{5.7.0} [Mekanism](Mekanism-v5.7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismInduction{5.7.0} [MekanismInduction](MekanismInduction-v5.7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismTools{5.7.0} [MekanismTools](MekanismTools-v5.7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    millenaire{5.1.11} [Millénaire](millenaire-jar-5.1.11) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minechem{5.05.71} [MineChem](MineChem-5.0.5-RC1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineChess{1.3.6} [MineChess](MineChess-1.3.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    numina{0.1.2-55} [Numina](Numina-1.6.2-0.1.2-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    powersuits{0.10.0-91} [MachineMuse's Modular Powersuits](ModularPowersuits-1.6.4-0.10.0-91.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_MovePlus{Version 2.2} [mod_MovePlus](moveplus v2.3 for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_MultiMine{1.3.1} [Multi Mine](MultiMine_1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.13.01} [Mystcraft](mystcraft-uni-1.6.4-0.10.13.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons{1.9.4.r51} [NEI Addons](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|AE{1.9.4.r51} [NEI Addons: Applied Energistics](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.9.4.r51} [NEI Addons: Crafting Tables](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.9.4.r51} [NEI Addons: Extra Bees](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Forestry{1.9.4.r51} [NEI Addons: Forestry](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|MiscPeripherals{1.9.4.r51} [NEI Addons: Misc Peripherals](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PetBat{1.2.8} [Pet Bat](PetBat_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    powersuitaddons{@VERSION@} [Andrew's Modular Powersuits Addons](powersuitaddons-1.6.4-884.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.2.2.19} [ProjectRed](ProjectRedBase-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatibility{1.0} [ProjRed|Compatibility](ProjectRedCompat-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{1.0} [ProjRed|Integration](ProjectRedIntegration-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{1.0} [ProjRed|Transmission](ProjectRedIntegration-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{1.0} [ProjRed|Illumination](ProjectRedLighting-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{1.0} [ProjRed|Expansion](ProjectRedMechanical-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{1.0} [ProjRed|Transportation](ProjectRedMechanical-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{1.0} [ProjRed|Exploration](ProjectRedWorld-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    QuantumCraft{1.1} [qCraft](qCraft1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DarrenPR_RottenFleshToLeather{1.0.0} [Rotten Flesh to Leather](RottenFleshToLeather_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{11.0} [Ruins Spawning System](Ruins_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Sync{2.1.1} [Sync](Sync2.1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{2.3-138} [Thaumic Tinkerer](ThaumicTinkerer-2.3-138.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    tradeboothmod{0.6.4.2} [Trade Booth Mod](tradebooth.0.6.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_UpdateCheck{1.1.1} [AtomicStryker Update Check Mod](UpdateCheckerMod_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{1.6.2 v1.13.6} [Balkon's WeaponMod](WeaponMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AIBlock{v1.0} [AIBlock](Weather v1.59 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WeatherMod{1.58} [Weather and Tornadoes](Weather v1.59 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WeepingAngels{1.2.0} [Weeping Angels Mod](WeepingAngels_1.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    witchery{0.18.4} [Witchery](witchery-1.6.4-0.18.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ZAMod{v1.9} [Zombie Awareness](Zombie Awareness v1.9 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.227} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.227} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct Environment: Sane and ready for action. Bugs may be reported.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 802 (44912 bytes; 0 MB) allocated, 802 (44912 bytes; 0 MB) used
    Player Count: 1 / 8; [GCCorePlayerMP['Gargoreis'/589, l='Fallu', x=316.12, y=70.00, z=-545.49]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

Having that issue, I put the old config back in and it worked fine, except of course no polytools and pills. This is what the old config looks like:
# Configuration file
###### 
# Output
###### 

Output {
}
###### 
# block
###### 

block {
    I:BluePrintPrinter=3997
    I:BlueprintProjector=4040
    I:ChemicalStorage=3998
    I:"Control Glass"=1181
    I:Decomposer=4042
    I:Emitter=1178
    I:FusionChamber=3999
    I:GhostBlock=4006
    I:"Infinite Emitter"=1182
    I:Microscope=4043
    I:"Polarized Glass"=1179
    I:"Series Receptor"=1180
    I:Synthesis=4041
    I:"Uranium Ore"=3996
}
###### 
# decomposerrecipe1
###### 

decomposerrecipe1 {
    S:Input=7:0
}
###### 
# decomposerrecipe1output1
###### 

decomposerrecipe1output1 {
    I:Amount=16
    I:ChemicalID=2
    B:IsMolecule=false
}
###### 
# item
###### 

item {
    I:AtomicManipulator=4739
    I:Blueprint=4741
    I:ChemistJournal=4743
    I:ChemistryTurtleUpgrade=4760
    I:Element=4736
    I:EmptyPills=4749
    I:FusionStar=4740
    I:Hammer=4748
    I:HazmatFeet=4744
    I:HazmatHead=4747
    I:HazmatLegs=4745
    I:HazmatTorso=4746
    I:Lens=4738
    I:Molecule=4737
    I:Polytool=4750
    I:TestTube=4742
}
###### 
# misc
###### 

misc {
    B:worldgen=true
}

**Comment by Maxwolf** [comment]
It sounds like you have a bad configuration file, try deleting it and letting it regen it looks like several things are missing from it.

**Comment by Gyramuur** [comment]
That's what I attempted, but doing so causes the aforementioned crash. Could you or someone else perchance post a working configuration file for me to try?

**Comment by Maxwolf** [comment]
The only other thing I could mention is perhaps you are using an out of date version of Universal Electricity. Older versions will throw the "canConnect" error since that is what changed in the API.

**Comment by Gyramuur** [comment]
Hmm...my Universal Electricity is 3.0.1.18, which is the latest for my modpack version (1.6.4), though no doubt ultimately out of date due to 1.7. I was able to start the game without Universal Electricity, but again, deleting the old minechem config causes a freeze on load.

**Comment by Maxwolf** [comment]
You need to be using UE 3.1x or higher to stop that error from happening. That would explain it :)

**Comment by Gyramuur** [comment]
Okay, I misread my version number of 3.0.1.18 thinking it was the latest for 1.6.4, but I went ahead and updated UE to 3.1.0.108 and it still freezes; it's not generating crash logs anymore, but it is freezing indefinitely until I shut it down. Any ideas on where I could get an updated config for minechem? ^^

**Comment by Gyramuur** [comment]
Nevermind, the reason it wasn't letting me craft or cheat the items was because they were having an item ID conflict with the lanterns and flashlights mod, but instead of the conflict causing a crash like usual, one mod simply overwrote the other's IDs. Thanks for your time ^^

**Comment by Maxwolf** [comment]
You are welcome! Glad to hear it is working!
