### ISSUE TITLE
Magical Crops issue

### ISSUE THREAD

**Issue by djolly78** [AdlyTempleton/MineChem#206]
hallo, find out that with minechem 5 BETA  + Magical Crops latest version installed its possible to get 1 diamond out of 1 Essence Dust when using the chemical synthesis machine
Maybe fix this.

**Comment by jakimfett** [comment]
@icke2002, can you please explain the process that you use to get a diamond from an essence dust, and also why this is broken/unbalanced/needs to be fixed? 

I'd also recommend that you go [get the latest version of Minechem from CurseForge](http://minecraft.curseforge.com/mc-mods/73373-minechem-5/files).

Here's [some guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting#is-it-a-bug) for what I'm looking for in a bug report and [what information to include in a bug report](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting#basic-requirements).

**Comment by jakimfett** [comment]
Closing this ticket due to lack of information. When submitting bug reports, please follow the [Minechem Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting) and include ALL required information.
