### ISSUE TITLE
Issue with Magic Crops

### ISSUE THREAD

**Issue by CharlieMcVicker** [AdlyTempleton/MineChem#209]
So i recently realized that the weak essence from Magic Crops is decomposed into 16 carbon nano tubes. This means a ore found below level 40 is equal to 4+ diamonds. I don't know if this was intentional or an issue with automatic chemical evaluation from crafting recipes...
Hope you find a fix!

**Comment by jakimfett** [comment]
What version of Minechem are you running? If you're not running 5.0.5-RC1, please go [download it from CurseForge](http://minecraft.curseforge.com/mc-mods/73373-minechem-5/files) and tell me if this is still a problem.

**Comment by jakimfett** [comment]
Given the lack of response and similarity to #212, I'm going to close this.
