### ISSUE TITLE
Pipes won't connect.

### ISSUE THREAD

**Issue by SirLuigi** [AdlyTempleton/MineChem#210]
I am trying to connect buildcraft kinesis pipes to a minechem machine but it won't connect.
I'm using MineChem v5.0.4 and Universal Electricity v3.10.0.114-core
![minechem_bug2](https://cloud.githubusercontent.com/assets/8009354/3418711/f7995016-fe4c-11e3-81ca-4915809eaa4e.png)

**Comment by Maxwolf** [comment]
Minechem 5.0.5 is the one which has my UE rewrite in it.

**Comment by jakimfett** [comment]
@SirLuigi please update to the [Minechem 5.0.5 RC1 (download it from CurseForge)](http://minecraft.curseforge.com/mc-mods/73373-minechem-5/files). If you're still having this issue after updating, please open a new ticket.
