### ISSUE TITLE
The machines cannot joint the pipeline.

### ISSUE THREAD

**Issue by zzgnn1010** [AdlyTempleton/MineChem#211]
There is no power supply, so the machine doesn't work.
Including  BC and TE pipeline.

**Comment by jakimfett** [comment]
Closing this ticket due to lack of information. When submitting bug reports, please follow the [Minechem Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting) and include ALL required information.
