### ISSUE TITLE
Minechem machines not connecting with Thermal Expansion energy conduits

### ISSUE THREAD

**Issue by asdfstickfigure** [AdlyTempleton/MineChem#213]
While I was starting to try and use MineChem, I attempted to use leadstone energy conduits to power the Chemical Decomposer. However, they never seem to connect to it, and don't provide any power to the device at all.
Here is a picture of what I'm trying to do: http://imgur.com/DxCIlHt,heCVgWO#0
I may be doing something stupid, in which case please tell me what I'm doing wrong.
Thanks!

**Comment by tarkyn** [comment]
It wil not work for me to

**Comment by asdfstickfigure** [comment]
Forgot to include my version. I'm on 5.05 RC1.

**Comment by asdfstickfigure** [comment]
Oops, found the fix. @tarkyn make sure to install Universal Energy Core, that should fix it!
