### ISSUE TITLE
Forestry Metal Multiplication in Decomposer

### ISSUE THREAD

**Issue by Revanchism** [AdlyTempleton/MineChem#214]
Minechem 5.0.5-RC1
FORESTRY-A-2.3.1.1
As part of YogscastComplete 2.8.7.5

A single metal bar from Forestry will output 81 of the constituent elements, well over the 16 required to combine back into dust. Does not affect any other mod's metals that were tested.

**Comment by jakimfett** [comment]
There's some other mod that is causing this. When I load up those versions, here's what I get (Forestry on the left, Mekanism copper on the right):
![](http://pics.jakimfett.com/2014-07-05_11-29-16.png)

EDIT: Scratch that...something weird is going on. When I load up Forestry in my IDE dev environment, everything decomposes as it should. When I load up Forestry normally, I can't get any of the ingots to decompose.

**Comment by jakimfett** [comment]
I just loaded up the Yogscastcomplete pack, and the copper/tin/bronze from Forestry do not decompose...right away.

I can place them into the decomposer and nothing happens. Then, once I remove them and exit the decomposer GUI, I have about two seconds of nothing happening, and then the GUI re-opens with several stacks of chemicals in it.

So, I'm not really sure what all is happening here. I need to talk to @maxwolf and see if he's got any insights.

**Comment by jakimfett** [comment]
If this issue persists in 1.7.10, please re-report it.
