### ISSUE TITLE
Galacticraft aluminum blocks creating strange output (v5.0.4)

### ISSUE THREAD

**Issue by BoredomKils** [AdlyTempleton/MineChem#215]
When I put an aluminium block into the chemical decomposer, it outputs Iron III Oxide, Copper, and Plutonium.  'Bout all there is to it.  Using v5.0.4, but will test with v5.0.5 RC1.

**Comment by jakimfett** [comment]
Please test this with v5.0.5-RC1, as many bugs were fixed in the 5.0.5 versions. Also, before submitting a bug report, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).

**Comment by BoredomKils** [comment]
Confirmed, happens with v5.0.5-RC1 as well.

**Comment by BoredomKils** [comment]
I've also noticed it's not just aluminum blocks from Galacticraft, it's a bunch of seemingly random blocks that output the same thing (like resonant energy cells from TE3).

**Comment by jakimfett** [comment]
Yeah, I'm getting reports of this from several people, looks like issue #214 has to do with the same problem.

**Comment by BoredomKils** [comment]
Yeah.  What's strange is the the items seem entirely unrelated, and all have this same, odd output (Factorization solar mirror, in this example): http://i.gyazo.com/8440a7ccb72c450501e40f8e8204f0ef.gif
My only guess is some sort of fail-safe for items not listed in the mod for decomposition, but of course it's not my place to say.

**Comment by jakimfett** [comment]
Well, the way it's _supposed_ to work is that the decomposer checks 2-3 "layers" deep into an item. Eg, item X is made from an iron and 4 redstone, which decompose into iron and...whatever redstone is supposed to be. The decomposer spits out the appropriate amount of materials for 1 iron and 4 redstone, and destroys item X.

For some reason, on some mod items, this isn't working. I've a sneaking hunch it's related to the Chrome decomp bug in #200, but I don't have any proof of that...yet. I do know that some of the mod items with weird or inconsistent outputs don't have any "normal" crafting recipes. For example, chromite is made from chromite flakes, but chromite flakes have no "normal" crafting recipe.

**Comment by jakimfett** [comment]
Nope, after doing some testing, #214 and #215 are NOT related to #200.

**Comment by bculkin2442** [comment]
I think that what's causing this is that it's picking up the TE recipes that use blazing pyrethrum, but don't have normal outputs.

**Comment by jakimfett** [comment]
Not necessarily, because it does this with JUST galacticraft and Minechem installed. I know it has something to do with the way I'm iterating through all the unadded recipes and trying to dynamically create decomp recipes for them.

**Comment by jakimfett** [comment]
Going to try and fix this in 1.7, closing this issue to clean up the bugtracker.
