### ISSUE TITLE
Mekanism power incompatibility (v5.0.5 RC1)

### ISSUE THREAD

**Issue by BoredomKils** [AdlyTempleton/MineChem#216]
When plugged directly into the output of a Mekanism energy cube, the game crashes giving this report:  http://pastebin.com/MhCy73Gy  Using v5.0.5 RC1, as well as Mekanism v6.0.5.46, if it helps.

**Comment by BoredomKils** [comment]
Happens with TE3 energy cells as well, http://pastebin.com/mnJjbQVY

Using v3.0.0.7 TE3.

**Comment by jakimfett** [comment]
What version of Universal Electricity Core are you running?

**Comment by BoredomKils** [comment]
Ah!  Never thought about that!  3.0.1.29

**Comment by jakimfett** [comment]
You need UE Core v3.1.x or higher for Minechem to work. Please update your UE Core file.
