### ISSUE TITLE
Decomposer and Synthesizer always use power

### ISSUE THREAD

**Issue by jakimfett** [AdlyTempleton/MineChem#217]
Tested using a Mekanism energy cube and universal cable. The machines use power all the time, when they should only use power when they're running. An Ultimate Energy Cube from Mekanism gets drained in about 4 minutes, give or take a bit.

Decomposer full of power:
![](http://pics.jakimfett.com/2014-07-05_18-27-26.png)

Energy cube after about 20 seconds:
![](http://pics.jakimfett.com/2014-07-05_18-29-06.png)

Energy cube after about 2 minutes:
![](http://pics.jakimfett.com/2014-07-05_18-30-14.png)

Energy cube after about 3 1/2 minutes:
![](http://pics.jakimfett.com/2014-07-05_18-31-53.png)

**Comment by jakimfett** [comment]
Hey @Maxwolf, any chance you could take a look at this for me? I'm not completely sure how all the UE stuff works, and at the very least I'd like to pick your brain about the energy transfer process.

**Comment by Maxwolf** [comment]
Check out the energy class, it works very similar to most other energy systems. You request energy to be filled into the machine and it will give you the amount requested (if it's available in the network).

Probably got your consume() function out in the open and nothing stopping it. If all else fails I will take a look, Mandrake was saying that he wanted me to add a config option for something also could do all that at once.

**Comment by jakimfett** [comment]
Closing issue to clean up the tracker.
