### ISSUE TITLE
OreDictionary oreUranium

### ISSUE THREAD

**Issue by FeldrinH** [AdlyTempleton/MineChem#219]
The chemical decomposer does not seem to support oreUranium. The IC2 experimental uranium does not decompose into uranium, even though it is registered as oreUranium just like the minechem uranium ore.

Minechem 5.0.5 RC1

**Comment by jakimfett** [comment]
This one is a bit tougher to fix than I thought, so it's not "fixed" per se, more that I've fixed oreGen (the config settings actually work now) and I made it so you can craft Minechem uranium from other mod uranium. It'll show up in the next release candidate.
