### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by calclavia** [AdlyTempleton/MineChem#22]
Not sure if already done, but would be nice to register sulfur as "dustSulfur" and uranium as "ingotUranium" in the ore dictionary for inter-mod compatibility.

**Comment by MFernflower** [comment]
Your now a contributor.. Feel free to add the code!

**Comment by calclavia** [comment]
I've 3 mods, don't have time :(

**Comment by MFernflower** [comment]
Thanks anyway!
