### ISSUE TITLE
Item ID wierdness

### ISSUE THREAD

**Issue by GamerInspired** [AdlyTempleton/MineChem#220]
There is two items per element e.g. there is two iron (Fe); look at image for examples. I have worked out it depends if the thing has been in a players inventory or not. I've been pulling them out of the chest then into my inventory then putting them back.

![report](https://cloud.githubusercontent.com/assets/8201304/3626312/f8e74114-0e7b-11e4-9c6b-481dbc85a0e7.png)

Feel free to ask for more information.

**Comment by jakimfett** [comment]
Do you get this with _just_ AE and Minechem installed? What versions of each? Could you please provide the information specified in the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting)?

**Comment by GamerInspired** [comment]
Sorry for the delay, I don't just get it with AE; also with vanilla chests, I'm using minecraft 1.5.2 so this issue might be fixed already.

(Will get you the specfic versions when I get home)

**Comment by jakimfett** [comment]
@GamerInspired - I'd highly recommend moving to 1.6.4, as I fixed around 50 bugs just for the Minechem 5.0.5 version alone.

**Comment by jakimfett** [comment]
Given that 1.5.2 is over a year out of date (1.6.1 released July 1st 2013), I'm closing this ticket. Please update to a more recent version of minecraft if you'd like support.
