### ISSUE TITLE
Add a config option to disable Chemical Enchantments

### ISSUE THREAD

**Issue by ReFleXisGod** [AdlyTempleton/MineChem#221]
Even though the chemical enchanting feature is very interesting it is very overpowered and even after balancing is not for some types of packs and servers. A config option to disable the chemical enchantment feature would be great.

**Comment by jakimfett** [comment]
Are you talking about how you can combine food with chemicals for special effects? Or are you talking about the polytool? Not exactly sure what you're asking for here...

**Comment by ReFleXisGod** [comment]
Chemicals on weapons.

**Comment by ReFleXisGod** [comment]
Or an option to disable all chemical type enchants.

**Comment by anishin** [comment]
All recipes "food + chemical element" in MineChem 5.0.5 (RC-1) add enchants! (I saw this in NEI in Cheat mode when press "X" key). Is it bug? I and ReFleXisGod want to disable this enchantments. (May be, you need to disable recipes "food + chemical element = food".)

**Comment by jakimfett** [comment]
So, if I'm understanding correctly...
You want a way to turn off combining chemicals with food (it's called "spiking", btw).
AND
You want a way to turn off chemicals applying to weapons.

Are there specific ones that you feel are "overpowered" or don't fit well? I'm interested in specific feedback, eg "applying chemical X unbalances gameplay in Y way" or "Having food with X chemical makes Y not work properly on my server".

**Comment by ReFleXisGod** [comment]
Yes, that would be great.

Aspirin:
Problem: Regeneration 2 for 3 minutes
What I would do: Regeneration 2 for 10 seconds (Not joking xD)

Tetrodotoxin:
Problem: Slowness & Wither 2 for 30 seconds
What I would do: Slowness for 5 seconds and Weakness 2 for 2 seconds

Testosterone:
Problem: Speed 2 and Strength 2 for 3 minutes
What I would do: Speed 2 and Strength 1 for 20 seconds

T-2 Mycotoxin:
Problem: Wither and weakness 4 for 2 minutes
What I would do: Wither for 5 seconds and weakness 2 for 10 seconds

Batchachotoxin:
Problem: Slowness, Wither 3 and Nausea 3 for 1 minute
What I would do: Slowness and Wither for 5 seconds.

There may be others, but they were the ones I noticed the most. I would keep visual effects such as blindness and nausea completely off chemical swords.

**Comment by jakimfett** [comment]
Do <strong>NOT</strong> close issues just to re-report them.

**Comment by MFernflower** [comment]
I assume he wants these values switchable in the config (mock config below):

 B:FoodSpiking=true
 B:SwordEffects=true

 Now that's fine and all but the constant nagging for them wasn't necessary.

**Comment by jakimfett** [comment]
Closing this issue to clean up the old issue tracker. See https://github.com/jakimfett/MineChem/issues/66 for the new ticket.
