### ISSUE TITLE
Translocators + decomposer crash on Resonant Rise pack.

### ISSUE THREAD

**Issue by mateon1** [AdlyTempleton/MineChem#224]
EDIT: Can't isolate what mods cause that, can only be reproduced on the Resonant Rise pack with recommended optional mods installed.

When a translocator transfers items into a decomposer, upon entering the world, the game crashes ([Like this](http://openeye.openmods.info/crashes/b650a07b0d211f9b1384b72d30b5bd21), [like this](http://openeye.openmods.info/crashes/3f9dd4fddd9b3744f8ad0710f7a4a5cb) and [like this](http://openeye.openmods.info/crashes/80e424e31e463d3c8f82b6e92acd7438)), this corrupts your world until you remove the translocator or decomposer with external tools such as MCEdit.

This bug only happens on the Resonant Rise pack installed from the ATLauncher with "Select recommended" button pressed, I can't seem to isolate what mods cause that, it's taking too much time.

How to reproduce:
Step one:
Setup a Minechem decomposer, and pump items from a chest into it using translocators.

Step two:
Exit the world.

Step three:
Re-enter the world. The game should crash when you enter.

Can this bug be reproduced with JUST MineChem installed?
No, this bug is a conflict between translocators mod, MineChem, and some other mods. It can only be reproduced with the Resonant Rise pack installed.

**Comment by jakimfett** [comment]
I've tried to reproduce this with the latest RR pack, and I can't. I'm going to go ahead and close this, if you're able to get this crash with the latest pack, go ahead and re-open it.
