### ISSUE TITLE
keratin recipe too large to synthesize

### ISSUE THREAD

**Issue by forestasog** [AdlyTempleton/MineChem#225]
recipe too large to fit in window

current recipe requires 10 slots, window only has 9

**Comment by MFernflower** [comment]
I can shorten it by a single amino acid. But dont molecules of the same type stack?

**Comment by forestasog** [comment]
the recipe is 3 threonine, 5 cysteine, 5 proline... i couldn't get them to stack, idk if there's some recipe unknown

**Comment by MFernflower** [comment]
Oh god, Its not registers as shapless for some reason. Ill figure out how to fix this asap

**Comment by MFernflower** [comment]
A fix is waiting. Thanks.

**Comment by MFernflower** [comment]
The new recipie is as follows:

keratin(146, new Molecule(threonine), new Molecule(cysteine), new Molecule(proline), new Molecule(threonine), new Molecule(proline), new Molecule(cysteine), new Molecule(proline));

**Comment by forestasog** [comment]
cool thx, i went over the other chem recipes and it didn't look like there were any others.

**Comment by jakimfett** [comment]
@forestasog - could I get you to test [Minechem build #85](http://jenkins.jakimfett.com/build/job/Minechem/85/) to see if that fixes this issue for you?

**Comment by forestasog** [comment]
can i install it into resonant rise modpack?

**Comment by jakimfett** [comment]
I dunno, can you? I give [permissions for any of my mods to be used in any modpack](http://jakimfett.com/status-report/modpacks/).

**Comment by forestasog** [comment]
idk lol, i don't really know how to install mods xD, i just did the atlauncher thing >.>

**Comment by jakimfett** [comment]
Well, this might be a good opportunity to learn how to edit packs in the ATLauncher. If you use google, you should be able to find a bunch of tutorials.

**Comment by forestasog** [comment]
k i just wanted to make sure it was possible

**Comment by forestasog** [comment]
i'm really new to this mod so idk if i'm the best tester lol. but off first observations i noticed that keratin costs less to make. also that leather now costs only keratin when before it cost keratin, glycine, and arginine.  i also don't really know anything about chemistry or if you're using realistic chemical formulas for these either.  atleast i can make leather now :)

**Comment by jakimfett** [comment]
Awesome, thanks for testing that! I'm going to mark this as "Done", go ahead and open a new issue if you run into anything else.
