### ISSUE TITLE
Crash-report

### ISSUE THREAD

**Issue by ResponsibleBear** [AdlyTempleton/MineChem#226]
Full log is here http://pastebin.com/y2DeNdKY
Plz help.

**Comment by jakimfett** [comment]
Please provide all the information required by the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting). Without information, I can't help you.

Just from a quick glance at your bug report, I saw that you're using Minechem 5.0.5-RC1. Please update to Minechem 5.0.5-RC2 and tell me if you can duplicate this bug, and **HOW** to duplicate it myself.

**Comment by jakimfett** [comment]
No response, closing ticket. Next time, follow the bug reporting guidelines.
