### ISSUE TITLE
Inventory Items don't render when using Polytool

### ISSUE THREAD

**Issue by king-of-ping** [AdlyTempleton/MineChem#227]
When adding many chemicals to Polytool, game stops rendering items in hotbar and inventory. See screenshot below.

Poly tool still consumes items but does not show them in orbit.

**Comment by king-of-ping** [comment]
![2014-08-02_19 31 53](https://cloud.githubusercontent.com/assets/8339080/3788714/5ec3d274-1a73-11e4-9928-d345c9e4b92d.png)

**Comment by king-of-ping** [comment]
Mod Pack: Yogscast Complete Pack 2.8.7.4-RR-YOGS

(MINECHEM-5.0.5-RC1)

**Comment by jakimfett** [comment]
I've poked this a bit, and haven't been able to find the root cause of this. Try putting fewer chemicals on your polytool...
