### ISSUE TITLE
Crash when placing Chemical Decomposer

### ISSUE THREAD

**Issue by Duros001** [AdlyTempleton/MineChem#228]
Using the latest build I am unable to place the chemical decomposer next to anything other than dirt/grass blocks, if I try to hook up leadstone conduits the game just crashes, and then just crashes when ever I try to reload that world.

I'm amazed that this isn't listed on here already as it happens 100% of the time for me, I'm using the FTB Monster mod-pack.

**Comment by jakimfett** [comment]
I don't believe that the FTB Monster pack has Minechem in it. Could you please provide me with the specific info I ask for in the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting)?

**Comment by jakimfett** [comment]
Ah, I found the bug. FTB Monster uses an outdated version of Universal Electricity (version 3.0.1.27) and Minechem requires UE v3.1+.
