### ISSUE TITLE
Pulling from a Chemicle Synthasis Machine

### ISSUE THREAD

**Issue by ViperByte** [AdlyTempleton/MineChem#229]
hi i play on the Yogscast Complete Pack/ Resonant Rise and no matter what i do i can seem to pull items from the synthases machine, i was going to use it in a automated ore quintupling with Mekanism, but it doesn't work, ive tried all of the pulling methods (Import bus, Retrieval node, transfer node, BC pipes, Mekanism pipes, logistic pipes.) and none seem to work. i read that there was an issue with this in the past but that was months ago and said it had been fixed with patch #72 so i downloaded the latests as the pack is behind and it still wont work.

If there is a fix that i don't know about please let me know. 

Thanks

**Comment by jakimfett** [comment]
Did you set the "AllowAutomation" to true in your config file?

**Comment by ViperByte** [comment]
probably not, i couldn't find it on the config

**Comment by jakimfett** [comment]
Then you're not using running Minechem 5.0.5-RC2, unless something went horribly wrong. I'll check to make sure nothing has changed, but please do confirm that you're running the RC2 of 5.0.5

**Comment by ViperByte** [comment]
ive reinstalled the latest version and i have it in the config :) thanks

**Comment by jakimfett** [comment]
No problem, I'll go ahead and close this issue.
