### ISSUE TITLE
Fusion Wall/ Tungsten Plating can be placed inside some other blocks, crashing clients in the area.

### ISSUE THREAD

**Issue by killfalcon** [AdlyTempleton/MineChem#230]
This is in Yogpack 2.9.3.0,so minechem 5.0.5-RC2, also seen on RC1 build.

Repro steps:
Place transfer pipe (not a node, just the regular pipe from ExtraUtils)
Right click reactor block on a Transfer Pipe.
Observe crash.
(you'll need to edit the block out to be able to get back into the area afterwards)

Crash report
http://openeye.openmods.info/crashes/f98894c63f4174f35660bcc41db9e92c

I think it's caused by the code that lets you put bits of the reactor in the ghost blocks the projector creates (which, BTW, is easily the coolest way to make multi-block structures I've seen).

I've specifically seen the issue with ExtraUtil's Transfer Pipes and buildcraft-style Pipes, I've not been able to replicate it with vanilla items like torches, glass, chests etc, or EnderIO conduits. I think it's micro blocks rather than transparency.

**Comment by jakimfett** [comment]
Thanks for the detailed description and reproduction steps, this is possibly my favorite crash report so far.

Just an FYI, [Particle Physics is no longer part of Minechem](http://jakimfett.com/status-report/splitting-minechem/), so in the future, please put issues with Particle Physics in the [Particle Physics issue tracker](https://github.com/jakimfett/ParticlePhysics/issues).

I'll take a look at this, but it may be a couple of days, I'm in the middle of moving to my new apartment, and my development desktop is currently in about six different boxes.

**Comment by jakimfett** [comment]
Fixed in code, it'll be in the next release candidate.
