### ISSUE TITLE
Increase power on polytool

### ISSUE THREAD

**Issue by bobsmith99** [AdlyTempleton/MineChem#232]
I kind of feel bad about posting this here because it probably isnt a bug, just my inability to figure out hoe this works, but here goes. I can't seem to get putting Lithium on the polytool to do anything. From what I understand after I put Li into the the tool when I get struck by lightning, such as from having gold also in the tool it should give the poly tool a charge and increase the damage it does, but when i get struck it doesnt seem to do anything. I am on version 5.05.88 in the latest resonant rise mainline modpack.

Again this probably isnt a bug and feel free to call me an idiot for not being able to figure this out, but it would be nice to be able to do some more damage with the polytool.

**Comment by jakimfett** [comment]
I'll have to talk to @Maxwolf, there was some power stuff that got removed when we moved from a custom power setup to the Universal Electricity API, and I seem to remember commenting out the "iterate through the inventory and give something a powerboost" code with the thought that I'd go back and fix it later.

As for giving the polytool a power boost...to be honest, I've been debating about removing the combat and tool abilities from the polytool completely, and instead turning it into a "module" for existing tools/weapons. For example, you could attach it to a sword to make a weapon that makes mobs float away, or on a tool to fertilize the ground. 

As it stands, the polytool does too much, and is too overpowered (eg, it's a diamond-level tool that never runs out or breaks). I'd probably adjust the recipe as well to be more balanced.

**Comment by jakimfett** [comment]
Yeah, it looks like I disabled the power stuff with the polytool. There are going to be changes in 1.7, so I'm probably not going to re-implement this.
