### ISSUE TITLE
Power and chest problems

### ISSUE THREAD

**Issue by jeromey127** [AdlyTempleton/MineChem#233]
Hi there,

I'm playing with the MineChem mod and over the past week i've noticed two bugs/issues.

The first one I came across was when I was in need of some quick diamonds, cutting a long story short, I noticed that the "Block of Diamond" is unable to be produced from the required ingredients in the Chemical Synthesis Machine, as it requires 1,200,000 units of power (i'm currently using RF) whereas my Chemical Synthesis Machine only holds a maximum of 1,022,220...

The second issue i'm having is using the "Chemical Storage Chest", firstly, I had to use the "/give" command, as I used to be able to craft one with a chest in the middle of a crafting bench with Lead all around it. However I've noticed that this recipe has been replaced for the "Leaded Chest", now that's not my problem, the problem is that i've noticed that there is no recipe for the Chemical Storage Chest, and also when it is acquired, it cannot be placed down by right clicking anywhere.

You may be aware of these bugs/issues but I thought I would still report them as the report could be useful.

Thank-you,

jeromey127 :)

**Comment by jakimfett** [comment]
Oi, thanks for the bug report. I'll take a look at the diamond block bug.

The chemical storage chest was replaced by the Leaded Chest. I added a warning message when you try to place down the chem storage chest.

**Comment by MFernflower** [comment]
A fix for the diamond block bug has been sent out. Thank you.

**Comment by jakimfett** [comment]
Fix has been accepted, once I fix the message for people attempting to place the chem storage chest (and maybe a few other fixes that I sneak in, just for kicks and giggles...), I'll push an RC3.

EDIT: Huh. Apparently my browser is being possessed. Sorry about that jeromy.
