### ISSUE TITLE
Microscope not craftable 

### ISSUE THREAD

**Issue by Thakao** [AdlyTempleton/MineChem#234]
I have installed Minechem 5.04 at first but i couldn't craft a microscope so i installed 5.05 RC2 but nothing changed.

**Comment by jakimfett** [comment]
Please include all the information required by the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting). I need more info as to why you can't craft the microscope. Can you craft the lens assembly? Does the recipe show up in NEI? Are you running a modpack? Have you tried Minechem in the vanilla launcher, without any other mods installed?

I'm able to craft the microscope with just Minechem 5.0.5-RC2 installed, and with Minechem installed alongside about 100 other mods.

Crafting recipe:
![](http://pics.jakimfett.com/2014-08-19-11:11:06.png)

Placed in the world:
![](http://pics.jakimfett.com/2014-08-19-11:13:02.png)

**Comment by jakimfett** [comment]
Closing, as I cannot reproduce, and there's been no response from @Thakao. If you still have this problem, please open a new ticket and follow the [Bug Reporting Guideline](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting)
