### ISSUE TITLE
Config: Disable Weapon/Food Spiking

### ISSUE THREAD

**Issue by ReFleXisGod** [AdlyTempleton/MineChem#235]
Add a config option to disable the spiking of food and weapons. It is quite OP for PvP servers.

**Comment by jakimfett** [comment]
Do <strong>NOT</strong> close issues just to re-report them. Doing so doesn't make me more likely to fix something, and it definitely doesn't make me want to add new features for you. 

If you'd done a bit of looking around, or even bothered to show up in IRC chat and ask, you'd know that I've been [struggling with a hand injury](http://jakimfett.com/status-report/whats-up-with-minechem/) and haven't been able to do much coding in the last few months.
