### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by suicidewooten** [AdlyTempleton/MineChem#237]
i cant hook power any kind of power to it i tryed them all in creative nothing worked

**Comment by MFernflower** [comment]
Install UE core. Also Im really getting tired of people using the bug report form to ask questions.

**Comment by jakimfett** [comment]
@suicidewooten , please go through the steps in the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting), and then open a new ticket. Also, reading up on the [Mod Installation Instructions](http://jakimfett.com/minecraft/minechem/) on the mod website.
