### ISSUE TITLE
[server][Forge 3.0.1208][Minechem 5.0.5.60] NoSuchFieldError: icons

### ISSUE THREAD

**Issue by wrothmonk** [AdlyTempleton/MineChem#239]
Running the mod client side works perfectly even with several other mods installed. However when I attempt to load it on the server, even by itself, it crashes with the main error appearing to be: NoSuchFieldError: icons

Full error log: http://pastebin.com/gb6J2hYy

**Comment by jakimfett** [comment]
Ah....it would help if I'd remembered to isolate clientside code to, well...the client. I'll fix this and release another alpha "soon".

**Comment by wrothmonk** [comment]
Not sure if I should open up a new issue on this as it seems you will but updating it anyway, so I'll just comment here. It seems that the particle physics portion of the mod isn't working. Neither the emitter block nor the glass types appear to be present.

**Comment by jakimfett** [comment]
@wrothmonk Particle Physics is no longer a part of Minechem, you can [read about it on my blog](http://jakimfett.com/status-report/splitting-minechem/). I haven't yet updated Particle Physics to 1.7.10

**Comment by wrothmonk** [comment]
Might want to update the minechem page then. It still shows up on the front page announcing that particle physics is part of minechem with nothing stating otherwise.

**Comment by jakimfett** [comment]
Fixed the icons issue, but the jarfile still isn't ready for servers. I'll announce it [on twitter](http://twitter.com/jakimfett) when it is.
