### ISSUE TITLE
Decomposer decomposing random chance way off

### ISSUE THREAD

**Issue by Timeslice42** [AdlyTempleton/MineChem#24]
In TileEntityDecomposer you have the following code (lines 153-156 as of now):
`if (recipe != null && recipe.getOutput() != null) {
            ArrayList<ItemStack> stacks = MinechemHelper.convertChemicalsIntoItemStacks(recipe.getOutput());
            placeStacksInBuffer(stacks);
        }`

Checking recipe.getOutput() against null and then calling it AGAIN causes the chances to be squared, or in otherwords for 20% it's actually 20% of a 20% chance to decompose.

It should actually be something like this:
`ArrayList<Chemical> output = recpice.getOutput();
        if (recipe != null && output != null) {
            ArrayList<ItemStack> stacks = MinechemHelper.convertChemicalsIntoItemStacks(output);
            placeStacksInBuffer(stacks);
        }`

**Comment by MFernflower** [comment]
Leave us a patch... Your help is appreciated!

**Comment by Timeslice42** [comment]
Sorry. Our server fork as quite different from your version of minechem. It would be more hassle than it would be worth for you to sort out the changes from a pull request.

**Comment by MFernflower** [comment]
I really like some of your changes! can you send us a pull request!

**Comment by Timeslice42** [comment]
I have sent this pull request. There's alot in there, so let me know if you have any questions. My steam account is Timeslice.

**Comment by MFernflower** [comment]
Danke!
