### ISSUE TITLE
 MineChem-5.0.5.72 Machines doesn't require energy to maintain

### ISSUE THREAD

**Issue by jawsawn** [AdlyTempleton/MineChem#242]
MineChem-5.0.5.72 both of the machines "Chemical Decomposer and Chemical Synthesizer " work without any power source. Synthesizer says "powered" without any power. 
Other Mods generating energy in pack: Mekanism7, Applied Energistics2, Extra Utilities

Is this a bug or don't we need energy anymore?

**Comment by jakimfett** [comment]
# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
