### ISSUE TITLE
Chemical Synthesizer is working wrong (1.7.10 v5.0.5.108)

### ISSUE THREAD

**Issue by jawsawn** [AdlyTempleton/MineChem#246]
Steps to reproduce:
1-Place a C.S. 
2-Power it from any sides
! It says its not powered in the gui
3-Put the recipe
! Only shift clicking works and you have to re-open the gui to get more items. And it sometimes dupes items

**Comment by jakimfett** [comment]
# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
