### ISSUE TITLE
Power Issues

### ISSUE THREAD

**Issue by cjay567** [AdlyTempleton/MineChem#247]
I'm using MineChem 5 and whenever i try to power any of the machines no power goes in. I can't use any of the machines because of this. I'm using Thermal Expansion Redstone Flux.

**Comment by jakimfett** [comment]
# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
