### ISSUE TITLE
Polytool information - Lithium - Obscure - Other problems

### ISSUE THREAD

**Issue by halander1** [AdlyTempleton/MineChem#248]
When placing large amounts of elements into the polytool, item sprites begin to disapear, along with my inventory, preventing me from fiddling with it more. Furthermore, the polytool info for lithium gives no information on what power means. Applied energistics power? Combat power ? :Lithium: A polytool infused with lithium can be infused with infinite amounts of power. Added power logarithmically contributes to damage. Can you please make the definition more understandable and also send me what the meaning of power is, so i can upgrade my tool ?

Furthermore, if you put a polytool in the center of a fusion reactor (or anything probably) and 2 chemicals on the side, and drain a fusion star, it starts going into the negatives and becomes infinitely usable.

Edit : The fusion star went into the negatives and was still usable even using normal chemicals (there was still a polytool in the center at onetime).

**Comment by jakimfett** [comment]
# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
