### ISSUE TITLE
Decomposer won't decompose Forestry Ores

### ISSUE THREAD

**Issue by pthivent** [AdlyTempleton/MineChem#249]
Playing Material Energy^3 1.4.5 which includes :
- Minecraft 1.6.4
- Forge 9.11.1.965
- Minechem 5.05
- Forestry 2.3.1.1 (703)
- Thermal Expansion 3.0.0.7
- Metallurgy 3.4.0

I tried to decompose some Forestry ores (Tin and Copper precisely) and noticed the decomposer won't process them. NEI tells me it should, the ore dictionary as well and it did work with Copper from Thermal Expansion (didn't test everything). 

Not really the same issue as #214 but somehow related (misbehavior with Forestry ores).

**Comment by jakimfett** [comment]
# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
