### ISSUE TITLE
Bukket in Microscope

### ISSUE THREAD

**Issue by JesperYssing** [AdlyTempleton/MineChem#251]
If i put the bucket in the microscope and press the Chemical Synthesis machine minecraft freezes and have to be restarted, tried it on a lan server and ended up with a corrupted world and it genereated the world again from scratch in 1.6.4 minechem version 5.0.5.
![minecraft_crash](https://cloud.githubusercontent.com/assets/8598392/4784639/ea88ddac-5d5f-11e4-863e-80397b437c95.png)

**Comment by jakimfett** [comment]
# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
