### ISSUE TITLE
Leather.

### ISSUE THREAD

**Issue by Derkudominus** [AdlyTempleton/MineChem#252]
When you shift drag leather you get 7 you get 2 if you just regular clicked.

**Comment by jakimfett** [comment]
# Please report bugs on the new bugtracker

Before reporting a new bug, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting).
Thank you!

[click to re-report this issue](https://github.com/jakimfett/Minechem/issues/new)
