### ISSUE TITLE
Add back build.xml for non-jenkins test builds! 

### ISSUE THREAD

**Issue by MFernflower** [AdlyTempleton/MineChem#28]

**Comment by keplersj** [comment]
Travis-CI build support? I did something like this with FossilArcheaology and LogisticsPipes

**Comment by keplersj** [comment]
If I write you an ant based build script would you like it to use MCP source obfuscation?

**Comment by MFernflower** [comment]
I don't care if the final jar is ran past obfuscation. Your call

**Comment by keplersj** [comment]
Sweet! I'm doing final testing today and tomorrow, but after that...

**Comment by MFernflower** [comment]
Please get it done ASAP.

**Comment by MFernflower** [comment]
Here is the old buildscript https://raw.github.com/perky/Minechem/master/build.xml
