### ISSUE TITLE
Server connection issues / ID mismatches

### ISSUE THREAD

**Issue by robaimes** [AdlyTempleton/MineChem#36]
http://puu.sh/3muAs.png

If a server has MineChem installed, but the client has MineChem and GregTech / ICBM (and presumably some other mods) installed, then this appears when connecting to a server, or loading an old world in SSP.

There is no obvious error for the mismatch in any of the configs, the ID's are the same in the Basic Components config and the MineChem config on both client and server. Even when I continue into an SSP world, the ID's remain the same for the items.

Not sure why this is happening, but for build 138 of MineChem this does NOT happen. In the more recent builds this happens.

**Comment by Rushmead** [comment]
You have Unsynced Server to Client Issues.. Copy and Paste Either Client to Server or Server To Client

**Comment by robaimes** [comment]
Copy and paste what exactly? If you mean the MineChem mod, they are the same, and if you mean configs, they are also the same.
