### ISSUE TITLE
Stacking problems.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [AdlyTempleton/MineChem#46]
There's a weird stacking problem since a while now.

Same base elements and molecules sometimes won't stack. Most often than not, after a while or after a relog they seem to stack again just fine.

It's quite annoying to have 20 carbon, 12 carbon, 10 carbon unable to stack for whatever weird reason.

**Comment by ghost** [comment]
Has something to do with radioactivity. After placing a radioactive element into a chemical storage and taking it back to your inventory, I was able stack some of the elements again, which didn't work before. It didn't work for all stacks, though
