### ISSUE TITLE
Fix these or MineChem is removed from Voltz

### ISSUE THREAD

**Issue by calclavia** [AdlyTempleton/MineChem#47]
http://forums.technicpack.net/threads/help-us-test-voltz-2-0.49398/#post-410308

**Comment by MFernflower** [comment]
I'm sorry. My lead devas are no where to be found. However Kepler said me and him will rewrite the engine for 1.6.2. I'm very concerned about this.

**Comment by MFernflower** [comment]
Please add me on Skype. My email is machacker9000@gmail.com

**Comment by MFernflower** [comment]
Also autocorrect sucks

**Comment by calclavia** [comment]
Just need these bugs fixed asap this weekend or we can't have MineChem in Voltz. Too buggy.
