### ISSUE TITLE
Jenkins Spamming

### ISSUE THREAD

**Issue by calclavia** [AdlyTempleton/MineChem#49]
Please fix your build script to include the BuildCraft API in the build because it is screwing up Jenkins and wasting my server's memory. Also please delete all your failed builds as once again disk space is getting scarce.

**Comment by Rushmead** [comment]
Ok Will do

**Comment by calclavia** [comment]
Remove all the broken builds on the Jenkins jobs ASAP.

**Comment by MFernflower** [comment]
Can I please have full perms?

**Comment by MFernflower** [comment]
So that I can clean it up

**Comment by calclavia** [comment]
You now have permission for MineChem.

**Comment by MFernflower** [comment]
I cannot physically remove that many builds. I give you permission to delete builds from #277 downwards

**Comment by calclavia** [comment]
There's no way that I know to automate build deleting. It's your/Rushmead's mod; you are responsible for keeping the build system clean. Either find a way to automate it (I'll happily install Jenkins addons) or do it manually. MineChem is taking up unnecessary space on my server.

**Comment by MFernflower** [comment]
May I ask what is the total HDD size of the server and how much is minechem taking up. There is also a plugin for people who want to watch there disk usage. https://wiki.jenkins-ci.org/display/JENKINS/Disk+Usage+Plugin

**Comment by calclavia** [comment]
Added plugin. Still you should delete some broken builds as they will eventually stack up and take too much space.

**Comment by MFernflower** [comment]
Ok
