### ISSUE TITLE
No download links?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [AdlyTempleton/MineChem#50]
There used to be all the newest release of minechem: http://universalelectricity.com/MineChem/downloads .

Now there's nothing. What happend?

**Comment by MFernflower** [comment]
We were updating the Jenkins. We did a few builds. And the builds are on the Jenkins. but they don't show up on cal's site.

**Comment by Unrepentant-Atheist** [comment]
Erm...there's a jenkins for minechem? I can has link plx?

**Comment by ghost** [comment]
http://calclavia.com:8080/job/MineChem/

**Comment by MFernflower** [comment]
Fixed
