### ISSUE TITLE
Copper, Tin, Silver ingots/ores not in working

### ISSUE THREAD

**Issue by regelneef** [AdlyTempleton/MineChem#51]
When I try to microscopically try to determine the makeup of copper, tin or silver ingots (I tried TE, IC2 ingots) the microscope does not recognize them. The same result with the ore's and nuggets. Steel ingots work just fine! Also the synthesizer won't make any copper ingots with 16 Cu elements (This is a guess, but I assumed this since the iron ingots took 16 iron elements) 

I used Minechem build 308 (latest) in combination with TE 2.4.6.0, IC2 build 1.117-385 with Forge 7.8.1.738 and FML 5.2.23.738 for Minecraft 1.5.2

Could someone please enlighten me what I'm doing wrong?

**Comment by Carcharhinidae** [comment]
have you tried using their respective dusts? at least for 1.6.2 you can't directly synthesize ingots, you can decompose them to their element but not make them directly.

**Comment by Rosethorns** [comment]
gold and iron ingots have no chemical synthesis recipe under the microscope. Intentional?

**Comment by AdlyTempleton** [comment]
The original problem was fixed a while back (They were never added in in the first place). Looking into not being able to synthesize ingots.
