### ISSUE TITLE
getMaxEnergyStored() returning incorrect value for TileEntitySynthesis and TileEntityDecomposer

### ISSUE THREAD

**Issue by NeoThunder** [AdlyTempleton/MineChem#58]
The `getMaxEnergyStored()` methods in both `TileEntitySynthesis` and `TileEntityDecomposer` classes return auto generated values instead of the corresponding `MAX_ENERGY_STORED` final values.

This causes the energy capacity of the Decomposer and Synthesis machines to work incorrectly (i.e. impossible to synthesize diamonds due to not enough energy stored).

**Comment by AdlyTempleton** [comment]
Fixed in 381
