### ISSUE TITLE
Decomposer does not return test tubes when decomposing compounds

### ISSUE THREAD

**Issue by Carcharhinidae** [AdlyTempleton/MineChem#64]
if you decompose a compound that's already from minechem itself (and as such already uses a test tube to even exist. say cellulose from a sapling into carbon, hydrogen and oxygen), you do not get that test tube back, and as such lose that test tube. 

to continue the example. cellulose should decompose into 21 tubes(6 carbon, 5 oxygen, 10 hydrogen), but only ' use up'  20 since it itself is already in a tube which should be returned. instead it uses 21 tubes.

**Comment by Rosethorns** [comment]
confirmed.

**Comment by AdlyTempleton** [comment]
Fixed in latest build
