### ISSUE TITLE
Charcoal has no composition

### ISSUE THREAD

**Issue by Rosethorns** [AdlyTempleton/MineChem#67]
Charcoal does not have a composition

**Comment by Vexatos** [comment]
Hmmm... Should be 8 carbon and 1 (leftover) cellulose for 'SuggestANumber' pieces of charcoal... agree?

**Comment by Rosethorns** [comment]
I'd agree with that. alternatively the flat 8 carbon would suffice.

**Comment by jakimfett** [comment]
Added composition for charcoal, also fixed some balance issues.
