### ISSUE TITLE
Nether Brick (item) has no composition

### ISSUE THREAD

**Issue by Rosethorns** [AdlyTempleton/MineChem#71]
Nether brick does not have a composition

**Comment by Vexatos** [comment]
What does nether brick consist of? It's compressed netherrack, so it should have the same components, maybe just a little more of it?

**Comment by Rosethorns** [comment]
cooked netherack actually. so swap the oxygen for carbon?

**Comment by Vexatos** [comment]
Agree.

**Comment by jakimfett** [comment]
Added a comp/decomp for netherbrick, will be fixed in dev3
