### ISSUE TITLE
No type of quartz (ore/item/block) has a composition

### ISSUE THREAD

**Issue by Rosethorns** [AdlyTempleton/MineChem#72]
No variant of quartz has a a composition despite being naturally occuring

**Comment by Vexatos** [comment]
Silicon dioxide for the item, together with some nether related components to differ from sand. The block, of course, 4 times as much as the item.

**Comment by MFernflower** [comment]
Sorry, I forgot to add the registration for nether quartz!

**Comment by jakimfett** [comment]
Quartz has a composition recipe now, closing this issue.
