### ISSUE TITLE
stacking issues with like elements and composition chemicals 

### ISSUE THREAD

**Issue by Rosethorns** [AdlyTempleton/MineChem#74]
same element items and same chemical compounds /can/ have issues stacking if they came from different decomposition "sessions"

example: 
Break down redstone, break down results to get oxygen.
Break down melon, break down water to get oxygen.
Oxygen from redstone products and oxygen from water products will not stack.

**Comment by speakerrob** [comment]
I have the same problem on build 4.2-18. However, even the same elements from the same source will not stack if created in different sessions. For instance, if I place a stack of cobblestone into the decomposer and obtain some Fe(Iron) that outputs into a chest, the next stack of cobblestone I put into the decomposer will sometimes output Fe that will not stack with the previous Fe already in the chest. Machines will also not pull Fe out of inventory if they don't "like" that version of the element. So sometimes it occurs where I have Fe to use in my inventory, but my machines will only see one stack of it and not the other.

The only thing I can think of, is that there is a date metadata being saved with the items that aren't matching so the same element types do not stack together if made in separate batches. That would make sense in the case of the radioactive elements, but I wouldn't expect that to be the case with the stable ones that don't have to track a decay time.

I'm using Fe as an example here, this occurs with other element types.
Also, in my case, I'm using Applied Energistics rv14 as my inventory. Although, the effect also occurs with vanilla chests.

_UPDATE_
I used an NBT editor to look at the nbt data on two Pb test tubes that were displaying this behavior, and I could not find any difference in the data. =/ I'm stumped, I was sure there would be some difference there.

Also, it seems that moving the item in and out of an inventory fixes the problem, but seems random.

**Comment by Perryman** [comment]
Using a unifier on some elements has allowed me to stack helium and hydrogen that was not previously stacking in an ME network.

**Comment by jakimfett** [comment]
Fixed in the latest dev build (Minechem 5.0.5-Dev).
