### ISSUE TITLE
Dupe: Using a factorization router you can pull infinite of the "result" from a Synthesis machine

### ISSUE THREAD

**Issue by Rosethorns** [AdlyTempleton/MineChem#75]
Using a factorization router you can pull infinite of the "result" from a Synthesis machine by setting it to extract from slot zero with a journal set to the recipe and no ingredients to make it

**Comment by AdlyTempleton** [comment]
Contacted factorization devs about this. Other automation methods seem to work perfectly, so I'm blaming this one on FC.

**Comment by Bunsan** [comment]
We have this same issue. Tested with TE item ducts and item translocators. Does not work with BC pipes. Have not tested AE or extra utilities yet. Tested forge 153 both sap and mcpc+.

**Comment by Bunsan** [comment]
This issue has been fixed now.  This can be closed.
