### ISSUE TITLE
Chemicals localization support

### ISSUE THREAD

**Issue by Vexatos** [AdlyTempleton/MineChem#81]
I wish localization support for all chemicals and their type (Halogen etc.)

**Comment by MFernflower** [comment]
It should be easy to find translated periodic tables.. its just coding the language registration for the element list is going to be annoying.

**Comment by Vexatos** [comment]
I am pretty sure the registration is the most annying of this, since there are unitary translations,so translating will be no problem, at least into German language. The rest of the tooltips though will be harder to translate, although just a very little.

**Comment by Vexatos** [comment]
Thanks!
