### ISSUE TITLE
BOP crash (1.6.4)

### ISSUE THREAD

**Issue by Leftorius** [AdlyTempleton/MineChem#84]
http://pastebin.com/93QGBvUt

**Comment by jakimfett** [comment]
I tested a random assortment of BoP flowers in both the microscope and the decomposer, and couldn't seem to duplicate the crash. 

I'm going to go ahead and close this, but I'll re-open it if you can provide me with a bit of extra info about what you attempted to do when this crashed, or if you can duplicate it with the latest build from from [CurseForge](http://minecraft.curseforge.com/mc-mods/minechem-5/files/) or the [Github releases page](https://github.com/jakimfett/MineChem/releases).
