### ISSUE TITLE
Chemical element enum

### ISSUE THREAD

**Issue by DarkGuardsman** [AdlyTempleton/MineChem#86]
Decided to create this list as i worked on compiling data on heating properties of elements. Thought i share it with you seeing as mine contains more data than your enum. Densities might be useful to your fluids as my pipes for FM now understand density. In which density will change how the fluid moves threw the pipe.
https://github.com/DarkGuardsman/Darks-CoreMachine/blob/master/src/com/builtbroken/common/ChemElement.java

I'm going to be added on to it more if you wish to use it. I might later this week add colors of the substances. I'll also be working on math helpers to calculate different properties of the elements. Mainly volume when pressure and temperature change. As well energy lose and gain when element change forms. 

I'm also planning on creating a GUI for a periodic table. I'm unsure if this mod contains one but if you would like i will share it with you. I'm mainly just creating it to test an idea of grid alignment based on arrays.

**Comment by jakimfett** [comment]
@DarkGuardsman did you end up doing anything with this?

**Comment by DarkGuardsman** [comment]
No, the mod that was using this stuff no longer exists. I merged it with Resonant Induction which at the moment doesn't have any chemical content planned. Considering i posted this 7 months ago a lot has changed and most of my plans scraped.

**Comment by jakimfett** [comment]
Ah, sad. Do you have a copy of the code anywhere? If not, oh well. The idea is sound, and I may use it in the future...maybe when I rework the decomposition process...

**Comment by DarkGuardsman** [comment]
I think for the decomposition process you need to focus on fixing oreName support. Right now a few IC2 and other mod ignots break down into the same few components. As well i suggest creating a reverse recipe finder to allow any object to be broken down. Another suggestion is to also look into using several machines for the process that including chemical storage tanks. That way breaking down a single stack of something doesn't clog the machines.

As for code here is the element enum https://github.com/DarkGuardsman/Built-Broken-Lib. There is another dev named MaxWolf that i've been talking to about it. What i've come up with is that using a database might be a better way than an enum. In which you can add only the elements and data you need. As well create recipes using the database rather than a few hundred lines of recipes.
