### ISSUE TITLE
IC2 Issue

### ISSUE THREAD

**Issue by remexre** [AdlyTempleton/MineChem#92]
http://pastebin.com/XDjj0efC

Seems to be IC2-related. I'm on build 401, from the IC2 Jenkins.

**Comment by diadistis** [comment]
I can confirm this. You can either downgrade MineChem to a compatible version with IC2 401 or download the latest experimental IC2.

**Comment by jakimfett** [comment]
This should have been fixed in the dev2 release...can you please let me know if it's still effecting you?
