### ISSUE TITLE
Crash on startup 'registerPotionEffectType'

### ISSUE THREAD

**Issue by lanord** [AdlyTempleton/MineChem#94]
Here is the crash report.

http://pastebin.com/QkST9hAh

**Comment by MFernflower** [comment]
Could be related to bukkit. Ill check it anyway

**Comment by MFernflower** [comment]
I have also sent in a fix for what could have went wrong.

**Comment by jakimfett** [comment]
Can't reproduce, closing ticket. If you can reproduce this issue using the latest dev release, please open a new ticket, @lanord
